"use client";
import {useMemo,useState} from "react"; import Link from "next/link"; import {useRouter} from "next/navigation"; import {ArrowLeft,Send} from "lucide-react"; import {createClient} from "@/lib/supabase/client";
type S={id:string;number:string;name:string|null;team:string};
export default function NewProposalClient({collectionId,recipientId,recipientName,offered,requested}:{collectionId:string;recipientId:string;recipientName:string;offered:S[];requested:S[]}){
 const supabase=useMemo(()=>createClient(),[]),router=useRouter(); const [message,setMessage]=useState(""); const [status,setStatus]=useState(""); const [sending,setSending]=useState(false);
 const send=async()=>{setSending(true);const {data,error}=await supabase.rpc("create_trade_proposal",{p_recipient_id:recipientId,p_collection_id:collectionId,p_offered:offered.map(s=>s.id),p_requested:requested.map(s=>s.id),p_message:message||null});setSending(false);if(error){setStatus("No se pudo enviar la propuesta.");return;}router.push(`/propuestas/${data}`);router.refresh();};
 return <main className="min-h-screen bg-[#f5f2e9] px-4 py-8"><div className="mx-auto max-w-3xl"><Link href="/mis-matches" className="flex items-center gap-2 text-sm font-bold"><ArrowLeft size={18}/>Volver a matches</Link><h1 className="mt-8 text-4xl font-black tracking-[-.05em]">Propuesta para {recipientName}</h1><p className="mt-2 text-[#65756b]">Revisa el intercambio antes de enviarlo.</p><div className="mt-7 grid gap-4 md:grid-cols-2"><Side title="Tú entregas" items={offered} tone="give"/><Side title="Tú recibes" items={requested} tone="receive"/></div><label className="mt-5 block text-sm font-bold">Mensaje opcional<textarea maxLength={500} value={message} onChange={e=>setMessage(e.target.value)} placeholder="¿Te parece bien este intercambio?" className="mt-2 min-h-24 w-full rounded-xl border border-[#173d2a]/20 bg-white p-4 outline-none"/></label><button onClick={send} disabled={sending} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#164f35] px-5 py-4 font-bold text-white disabled:opacity-50"><Send size={18}/>{sending?"Enviando…":"Enviar propuesta"}</button>{status&&<p role="status" className="mt-3 rounded-xl bg-white p-3 text-sm font-bold">{status}</p>}</div></main>;
}
function Side({title,items,tone}:{title:string;items:S[];tone:"give"|"receive"}){return <section className={`rounded-2xl p-5 ${tone==="give"?"bg-[#f7fbdc]":"bg-[#fff0e8]"}`}><h2 className="font-black">{title} · {items.length}</h2><div className="mt-3 flex flex-wrap gap-2">{items.map(s=><span key={s.id} className={`rounded-lg px-3 py-2 text-xs font-bold ${tone==="give"?"bg-[#c9f31d]":"bg-[#ff6a3d] text-white"}`}>#{s.number} · {s.name??s.team}</span>)}</div></section>}
