import Link from "next/link";
import { ArrowRight, Check, CircleDollarSign, Repeat2, Search, Store } from "lucide-react";
import BrandLogo from "@/components/brand-logo";

const steps = [
  { number: "01", title: "marca lo importante", text: "Añade únicamente los cromos que te faltan y los que tienes repetidos." },
  { number: "02", title: "encuentra coincidencias", text: "CromoNexo localiza coleccionistas que tienen lo que buscas y necesitan lo que tú tienes." },
  { number: "03", title: "elige cómo conseguirlo", text: "Propón un intercambio o utiliza el mercado para comprar y vender directamente." },
];

export default function LandingPage() {
  return <main className="landing-page overflow-hidden">
    <header className="landing-header"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 md:px-8">
      <Link href="/" className="flex items-center gap-2.5 text-xl font-black tracking-[-.045em]"><BrandLogo/><span>Cromo<span className="text-[#8dbd12]">Nexo</span></span></Link>
      <nav className="hidden items-center gap-8 text-sm font-semibold text-[#555b57] md:flex"><a href="#como-funciona">cómo funciona</a><a href="#posibilidades">posibilidades</a><Link href="/login">iniciar sesión</Link></nav>
      <Link href="/login" className="landing-nav-cta">crear cuenta</Link>
    </div></header>

    <section className="landing-hero mx-auto grid max-w-7xl items-center gap-12 px-5 pb-16 pt-10 md:px-8 lg:grid-cols-[1.08fr_.92fr] lg:pb-24 lg:pt-16">
      <div><p className="landing-kicker">cromos · intercambios · mercado</p><h1><span className="hero-title-line">tu colección.</span><span className="hero-title-accent">sin</span><span className="hero-title-accent">complicaciones.</span></h1><p className="landing-lead">Organiza tus faltantes y repetidos, encuentra coleccionistas compatibles y decide si quieres intercambiar, comprar o vender.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/login" className="landing-primary-action">empezar gratis <ArrowRight size={19}/></Link><a href="#como-funciona" className="landing-secondary-action">ver cómo funciona</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm font-medium text-[#666d68]"><span className="flex items-center gap-2"><Check size={17} className="text-[#79a900]"/>sin marcar todo el álbum</span><span className="flex items-center gap-2"><Check size={17} className="text-[#79a900]"/>gratis para empezar</span></div></div>
      <div className="landing-product-card"><div className="flex items-center justify-between"><div><p className="landing-kicker text-white/45">mi colección</p><p className="mt-2 text-2xl font-semibold text-white">LALIGA ESTE 2026/27</p></div><span className="landing-live-dot">activa</span></div><div className="mt-12 grid grid-cols-2 gap-3"><Metric value="42" label="me faltan" accent/><Metric value="27" label="repetidos"/></div><div className="mt-4 rounded-[1.35rem] bg-white p-4 text-[#101311]"><div className="flex items-center justify-between"><p className="text-sm font-semibold">últimos cromos</p><Search size={17} className="text-[#727873]"/></div><div className="mt-4 space-y-2"><Sticker number="12" status="me falta"/><Sticker number="47" status="repetido"/><Sticker number="83" status="me falta"/></div></div><div className="landing-match"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#b6ef22] text-black"><Repeat2 size={18}/></span><span><small>nuevo match</small><strong>8 cromos compatibles</strong></span><ArrowRight size={18}/></div></div>
    </section>

    <section id="como-funciona" className="landing-dark-section"><div className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><p className="landing-kicker text-[#b6ef22]">así funciona</p><div className="mt-5 grid gap-6 lg:grid-cols-2 lg:items-end"><h2>menos listas.<br/>más conexiones.</h2><p className="max-w-lg text-lg leading-8 text-white/55">Convertimos la información de tu colección en oportunidades reales con otros coleccionistas.</p></div><div className="mt-14 grid border-t border-white/15 md:grid-cols-3">{steps.map(step=><article key={step.number} className="landing-step"><span>{step.number}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></div></section>

    <section id="posibilidades" className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><div className="grid gap-8 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="landing-kicker text-[#698a16]">todo conectado</p><h2 className="landing-section-title">una colección que trabaja para ti.</h2><p className="mt-5 max-w-md text-lg leading-8 text-[#666d68]">Tus repetidos dejan de estar parados y tus faltantes dejan de ser una búsqueda interminable.</p></div><div className="grid gap-3"><Feature icon={<Repeat2/>} title="intercambia" text="Recibe matches ordenados por compatibilidad y prepara propuestas claras."/><Feature icon={<Store/>} title="vende" text="Publica cualquier cromo que tengas y gestiona las solicitudes recibidas."/><Feature icon={<CircleDollarSign/>} title="compra" text="Encuentra publicaciones de otros coleccionistas y solicita el cromo que buscas."/></div></div></section>

    <section className="landing-final-cta"><div className="mx-auto max-w-4xl px-5 py-16 text-center md:py-24"><p className="landing-kicker">empieza hoy</p><h2>pon tu colección en movimiento.</h2><p className="mx-auto mt-5 max-w-xl text-lg text-black/60">Crea tu cuenta, añade tus cromos y descubre tus primeras coincidencias.</p><Link href="/login" className="mt-8 inline-flex min-h-14 items-center justify-center gap-2 rounded-full bg-black px-8 font-semibold text-white">crear mi cuenta <ArrowRight size={19}/></Link></div></section>
    <footer className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-9 text-sm text-[#6b716d] md:px-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="font-black text-[#101311]">Cromo<span className="text-[#8dbd12]">Nexo</span></p><p>hecho para coleccionistas · @cromonexo</p></div><nav className="flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold"><Link href="/ayuda">ayuda</Link><Link href="/contacto">contacto</Link><Link href="/aviso-legal">aviso legal</Link><Link href="/privacidad">privacidad</Link><Link href="/condiciones">condiciones de uso</Link></nav></footer>
  </main>;
}

function Metric({value,label,accent=false}:{value:string;label:string;accent?:boolean}) { return <div className={`rounded-[1.35rem] p-5 ${accent?"bg-[#b6ef22] text-black":"bg-[#252a27] text-white"}`}><strong className="text-4xl font-semibold tracking-[-.06em]">{value}</strong><p className={`mt-2 text-sm ${accent?"text-black/60":"text-white/45"}`}>{label}</p></div> }
function Sticker({number,status}:{number:string;status:string}) { return <div className="flex items-center gap-3 rounded-xl bg-[#f1f3f0] p-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-black text-xs font-semibold text-white">{number}</span><span className="flex-1 text-sm font-medium">cromo #{number}</span><span className="rounded-full bg-white px-3 py-1 text-[11px] font-semibold text-[#555b57]">{status}</span></div> }
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}) { return <article className="landing-feature"><span>{icon}</span><div><h3>{title}</h3><p>{text}</p></div><ArrowRight className="ml-auto shrink-0" size={20}/></article> }
