-- Catálogo extraído del checklist MGK 2026/27 facilitado para CromoNexo.
insert into public.collections (slug, name, season, publisher, total_stickers, is_active)
values ('megacracks-2026-27', 'MegaCracks 2026/27', '2026/27', 'Panini', 519, true)
on conflict (slug) do update set name=excluded.name, total_stickers=excluded.total_stickers, is_active=true;

insert into public.stickers (collection_id, number, name, team, category)
select c.id, v.number, v.name, v.team, v.category
from public.collections c
cross join (values
  ('1', 'Barrios Atlético', 'Elite', 'elite'),
  ('2', 'Bellingham Real Madrid', 'Elite', 'elite'),
  ('3', 'Budimir Osasuna', 'Elite', 'elite'),
  ('4', 'Courtois Real Madrid', 'Elite', 'elite'),
  ('5', 'Fede Valverde Real Madrid', 'Elite', 'elite'),
  ('6', 'Fermín Barcelona', 'Elite', 'elite'),
  ('7', 'Giuliano Atlético', 'Elite', 'elite'),
  ('8', 'Julián Álvarez Atlético', 'Elite', 'elite'),
  ('9', 'Lamine Yamal Barcelona', 'Elite', 'elite'),
  ('10', 'Mbappé Real Madrid', 'Elite', 'elite'),
  ('11', 'Moleiro Villarreal', 'Elite', 'elite'),
  ('12', 'Nico Williams Athletic', 'Elite', 'elite'),
  ('13', 'Oyarzabal Real Sociedad', 'Elite', 'elite'),
  ('14', 'Pablo Fornals Betis', 'Elite', 'elite'),
  ('15', 'Pedri Barcelona', 'Elite', 'elite'),
  ('16', 'Raphinha Barcelona', 'Elite', 'elite'),
  ('17', 'Unai Simón Athletic', 'Elite', 'elite'),
  ('18', 'Vinícius Real Madrid', 'Elite', 'elite'),
  ('1P', 'Barrios Atlético', 'Elite Power', 'elite power'),
  ('2P', 'Bellingham Real Madrid', 'Elite Power', 'elite power'),
  ('3P', 'Budimir Osasuna', 'Elite Power', 'elite power'),
  ('4P', 'Courtois Real Madrid', 'Elite Power', 'elite power'),
  ('5P', 'Fede Valverde Real Madrid', 'Elite Power', 'elite power'),
  ('6P', 'Fermín Barcelona', 'Elite Power', 'elite power'),
  ('7P', 'Giuliano Atlético', 'Elite Power', 'elite power'),
  ('8P', 'Julián Álvarez Atlético', 'Elite Power', 'elite power'),
  ('9P', 'Lamine Yamal Barcelona', 'Elite Power', 'elite power'),
  ('10P', 'Mbappé Real Madrid', 'Elite Power', 'elite power'),
  ('11P', 'Moleiro Villarreal', 'Elite Power', 'elite power'),
  ('12P', 'Nico Williams Athletic', 'Elite Power', 'elite power'),
  ('13P', 'Oyarzabal Real', 'Elite Power', 'elite power'),
  ('14P', 'Pablo Fornals Betis', 'Elite Power', 'elite power'),
  ('15P', 'Pedri Barcelona', 'Elite Power', 'elite power'),
  ('16P', 'Raphinha Barcelona', 'Elite Power', 'elite power'),
  ('17P', 'Unai Simón Athletic', 'Elite Power', 'elite power'),
  ('18P', 'Vinícius Real Madrid', 'Elite Power', 'elite power'),
  ('19', 'Escudo', 'Deportivo Alavés', null),
  ('20', 'Sivera', 'Deportivo Alavés', 'portero'),
  ('21', null, 'Deportivo Alavés', null),
  ('22', 'Jonny', 'Deportivo Alavés', 'defensa'),
  ('23', 'Tenaglia', 'Deportivo Alavés', 'defensa'),
  ('24', 'Koski', 'Deportivo Alavés', 'defensa'),
  ('25', 'Parada', 'Deportivo Alavés', 'defensa'),
  ('26', 'Yusi', 'Deportivo Alavés', 'defensa'),
  ('27', 'Benavidez', 'Deportivo Alavés', 'medio'),
  ('28', 'Blanco', 'Deportivo Alavés', 'medio'),
  ('29', 'Guevara', 'Deportivo Alavés', 'medio'),
  ('30', 'Aleñá', 'Deportivo Alavés', 'medio'),
  ('31', 'Pablo Ibáñez', 'Deportivo Alavés', 'medio'),
  ('32', 'Denis Suárez', 'Deportivo Alavés', 'medio'),
  ('33', 'Ángel Pérez', 'Deportivo Alavés', 'delantero'),
  ('34', 'Abde', 'Deportivo Alavés', 'delantero'),
  ('35', 'Toni Martínez', 'Deportivo Alavés', 'delantero'),
  ('36', 'Boyé', 'Deportivo Alavés', 'delantero'),
  ('37', 'Escudo', 'Athletic Club de Bilbao', null),
  ('38', 'Unai Simón', 'Athletic Club de Bilbao', 'portero'),
  ('39', 'Padilla', 'Athletic Club de Bilbao', 'portero'),
  ('40', 'Areso', 'Athletic Club de Bilbao', 'defensa'),
  ('41', 'Vivian', 'Athletic Club de Bilbao', 'defensa'),
  ('42', 'Paredes', 'Athletic Club de Bilbao', 'defensa'),
  ('43', 'Laporte', 'Athletic Club de Bilbao', 'defensa'),
  ('44', 'Yuri', 'Athletic Club de Bilbao', 'defensa'),
  ('45', 'Ruiz de Galarreta', 'Athletic Club de Bilbao', 'medio'),
  ('46', 'Jauregizar', 'Athletic Club de Bilbao', 'medio'),
  ('47', 'Rego', 'Athletic Club de Bilbao', 'medio'),
  ('48', 'Sancet', 'Athletic Club de Bilbao', 'medio'),
  ('49', 'Nico Serrano', 'Athletic Club de Bilbao', 'medio'),
  ('50', 'Berenguer', 'Athletic Club de Bilbao', 'delantero'),
  ('51', 'Robert Navarro', 'Athletic Club de Bilbao', 'delantero'),
  ('52', 'Williams', 'Athletic Club de Bilbao', 'delantero'),
  ('53', 'Guruzeta', 'Athletic Club de Bilbao', 'delantero'),
  ('54', 'Nico Williams', 'Athletic Club de Bilbao', 'delantero'),
  ('55', 'Escudo', 'Atlético de Madrid', null),
  ('56', 'Oblak', 'Atlético de Madrid', 'portero'),
  ('57', 'Musso', 'Atlético de Madrid', 'portero'),
  ('58', 'Marcos Llorente', 'Atlético de Madrid', 'defensa'),
  ('59', 'Le Normand', 'Atlético de Madrid', 'defensa'),
  ('60', 'Pubill', 'Atlético de Madrid', 'defensa'),
  ('61', 'Giménez', 'Atlético de Madrid', 'defensa'),
  ('62', 'Hancko', 'Atlético de Madrid', 'defensa'),
  ('63', 'Ruggeri', 'Atlético de Madrid', 'defensa'),
  ('64', 'Koke', 'Atlético de Madrid', 'medio'),
  ('65', 'Barrios', 'Atlético de Madrid', 'medio'),
  ('66', 'Johnny Cardoso', 'Atlético de Madrid', 'medio'),
  ('67', 'Álex Baena', 'Atlético de Madrid', 'medio'),
  ('68', 'Almada', 'Atlético de Madrid', 'medio'),
  ('69', 'Giuliano', 'Atlético de Madrid', 'delantero'),
  ('70', 'Lookman', 'Atlético de Madrid', 'delantero'),
  ('71', 'Julián Alvarez', 'Atlético de Madrid', 'delantero'),
  ('72', 'Sorloth', 'Atlético de Madrid', 'delantero'),
  ('73', 'Escudo', 'FC Barcelona', null),
  ('74', 'Joan García', 'FC Barcelona', 'portero'),
  ('75', 'Szczesny', 'FC Barcelona', 'portero'),
  ('76', 'Koundé', 'FC Barcelona', 'defensa'),
  ('77', 'Gerard Martín', 'FC Barcelona', 'defensa'),
  ('78', 'Cubarsí', 'FC Barcelona', 'defensa'),
  ('79', 'Eric García', 'FC Barcelona', 'defensa'),
  ('80', 'Araújo', 'FC Barcelona', 'defensa'),
  ('81', 'Balde', 'FC Barcelona', 'defensa'),
  ('82', 'De Jong', 'FC Barcelona', 'medio'),
  ('83', 'Marc Bernal', 'FC Barcelona', 'medio'),
  ('84', 'Gavi', 'FC Barcelona', 'medio'),
  ('85', 'Pedri', 'FC Barcelona', 'medio'),
  ('86', 'Fermín', 'FC Barcelona', 'medio'),
  ('87', 'Dani Olmo', 'FC Barcelona', 'delantero'),
  ('88', 'Raphinha', 'FC Barcelona', 'delantero'),
  ('89', 'Lamine Yamal', 'FC Barcelona', 'delantero'),
  ('90', 'Ferran Torres', 'FC Barcelona', 'delantero'),
  ('91', 'Escudo', 'Real Betis', null),
  ('92', 'Valles', 'Real Betis', 'portero'),
  ('93', 'Pau López', 'Real Betis', 'portero'),
  ('94', 'Aitor Ruibal', 'Real Betis', 'defensa'),
  ('95', 'Bartra', 'Real Betis', 'defensa'),
  ('96', 'Diego Llorente', 'Real Betis', 'defensa'),
  ('97', 'Natan', 'Real Betis', 'defensa'),
  ('98', 'Valentín Gómez', 'Real Betis', 'defensa'),
  ('99', 'Marc Roca', 'Real Betis', 'medio'),
  ('100', 'Amrabat', 'Real Betis', 'medio'),
  ('101', 'Fidalgo', 'Real Betis', 'medio'),
  ('102', 'Pablo Fornals', 'Real Betis', 'medio'),
  ('103', 'Lo Celso', 'Real Betis', 'medio'),
  ('104', 'Isco', 'Real Betis', 'medio'),
  ('105', 'Riquelme', 'Real Betis', 'delantero'),
  ('106', 'Antony', 'Real Betis', 'delantero'),
  ('107', 'Cucho Hernández', 'Real Betis', 'delantero'),
  ('108', 'Abde', 'Real Betis', 'delantero'),
  ('109', 'Escudo', 'RC Celta de Vigo', null),
  ('110', 'Radu', 'RC Celta de Vigo', 'portero'),
  ('111', 'Iván Villar', 'RC Celta de Vigo', 'portero'),
  ('112', 'Javi Rueda', 'RC Celta de Vigo', 'defensa'),
  ('113', 'Álvaro Núñez', 'RC Celta de Vigo', 'defensa'),
  ('114', 'Javi Rodríguez', 'RC Celta de Vigo', 'defensa'),
  ('115', 'Starfelt', 'RC Celta de Vigo', 'defensa'),
  ('116', 'Marcos Alonso', 'RC Celta de Vigo', 'defensa'),
  ('117', 'Carreira', 'RC Celta de Vigo', 'defensa'),
  ('118', 'Ilaix Moriba', 'RC Celta de Vigo', 'medio'),
  ('119', 'Miguel Román', 'RC Celta de Vigo', 'medio'),
  ('120', 'Hugo Álvarez', 'RC Celta de Vigo', 'medio'),
  ('121', 'Fer López', 'RC Celta de Vigo', 'medio'),
  ('122', 'Swedberg', 'RC Celta de Vigo', 'medio'),
  ('123', 'Pablo Durán', 'RC Celta de Vigo', 'delantero'),
  ('124', 'Iago Aspas', 'RC Celta de Vigo', 'delantero'),
  ('125', 'Borja Iglesias', 'RC Celta de Vigo', 'delantero'),
  ('126', 'Jutglà', 'RC Celta de Vigo', 'delantero'),
  ('127', 'Escudo', 'Deportivo', null),
  ('128', 'Álvaro Fernández', 'Deportivo', 'portero'),
  ('129', 'Germán Parreño', 'Deportivo', 'portero'),
  ('130', 'Adrià Altimira', 'Deportivo', 'defensa'),
  ('131', 'Loureiro', 'Deportivo', 'defensa'),
  ('132', 'Noubi', 'Deportivo', 'defensa'),
  ('133', 'Dani Barcia', 'Deportivo', 'defensa'),
  ('134', 'Arnau Comas', 'Deportivo', 'defensa'),
  ('135', 'Quagliata', 'Deportivo', 'defensa'),
  ('136', 'Villares', 'Deportivo', 'medio'),
  ('137', 'Riki', 'Deportivo', 'medio'),
  ('138', 'Mario Soriano', 'Deportivo', 'medio'),
  ('139', 'José Ángel', 'Deportivo', 'medio'),
  ('140', 'Luismi Cruz', 'Deportivo', 'medio'),
  ('141', 'Mella', 'Deportivo', 'medio'),
  ('142', 'Yeremay', 'Deportivo', 'delantero'),
  ('143', 'Eddahchouri', 'Deportivo', 'delantero'),
  ('144', 'Bil Nsongo', 'Deportivo', 'delantero'),
  ('145', 'Escudo', 'Elche CF', null),
  ('146', 'Dituro', 'Elche CF', 'portero'),
  ('147', null, 'Elche CF', null),
  ('148', null, 'Elche CF', null),
  ('149', 'Chust', 'Elche CF', 'defensa'),
  ('150', 'Bigas', 'Elche CF', 'defensa'),
  ('151', 'Affengruber', 'Elche CF', 'defensa'),
  ('152', 'Pedrosa', 'Elche CF', 'defensa'),
  ('153', 'Germán Valera', 'Elche CF', 'medio'),
  ('154', 'Gonzalo Villar', 'Elche CF', 'medio'),
  ('155', 'Martim Neto', 'Elche CF', 'medio'),
  ('156', 'Marc Aguado', 'Elche CF', 'medio'),
  ('157', null, 'Elche CF', null),
  ('158', 'Morente', 'Elche CF', 'medio'),
  ('159', null, 'Elche CF', null),
  ('160', 'Diangana', 'Elche CF', 'delantero'),
  ('161', 'Yago Santiago', 'Elche CF', 'delantero'),
  ('162', 'Cepeda', 'Elche CF', 'delantero'),
  ('163', 'Escudo', 'RCD Espanyol', null),
  ('164', 'Dmitrovic', 'RCD Espanyol', 'portero'),
  ('165', 'Fortuño', 'RCD Espanyol', 'portero'),
  ('166', 'El Hilali', 'RCD Espanyol', 'defensa'),
  ('167', 'Rubén Sánchez', 'RCD Espanyol', 'defensa'),
  ('168', 'Riedel', 'RCD Espanyol', 'defensa'),
  ('169', 'Cabrera', 'RCD Espanyol', 'defensa'),
  ('170', 'Miguel Rubio', 'RCD Espanyol', 'defensa'),
  ('171', null, 'RCD Espanyol', null),
  ('172', 'Urko', 'RCD Espanyol', 'medio'),
  ('173', 'Pol Lozano', 'RCD Espanyol', 'medio'),
  ('174', 'Edu Expósito', 'RCD Espanyol', 'medio'),
  ('175', 'Jofre', 'RCD Espanyol', 'medio'),
  ('176', 'Dolan', 'RCD Espanyol', 'delantero'),
  ('177', 'Puado', 'RCD Espanyol', 'delantero'),
  ('178', 'Roberto Fernández', 'RCD Espanyol', 'delantero'),
  ('179', 'Kike García', 'RCD Espanyol', 'delantero'),
  ('180', 'Pere Milla', 'RCD Espanyol', 'delantero'),
  ('181', 'Escudo', 'Getafe CF', null),
  ('182', 'David Soria', 'Getafe CF', 'portero'),
  ('183', 'Letacek', 'Getafe CF', 'portero'),
  ('184', 'Kiko Femenía', 'Getafe CF', 'defensa'),
  ('185', 'Djené', 'Getafe CF', 'defensa'),
  ('186', 'Boselli', 'Getafe CF', 'defensa'),
  ('187', 'Abqar', 'Getafe CF', 'defensa'),
  ('188', 'Zaid Romero', 'Getafe CF', 'defensa'),
  ('189', 'Davinchi', 'Getafe CF', 'defensa'),
  ('190', 'Mario Martín', 'Getafe CF', 'medio'),
  ('191', 'Javi Muñoz', 'Getafe CF', 'medio'),
  ('192', null, 'Getafe CF', null),
  ('193', null, 'Getafe CF', null),
  ('194', null, 'Getafe CF', null),
  ('195', 'Borja Mayoral', 'Getafe CF', 'delantero'),
  ('196', 'Luis Vázquez', 'Getafe CF', 'delantero'),
  ('197', 'Satriano', 'Getafe CF', 'delantero'),
  ('198', 'Álex Sancris', 'Getafe CF', 'delantero'),
  ('199', 'Escudo', 'Levante UD', null),
  ('200', 'Ryan', 'Levante UD', 'portero'),
  ('201', 'Pablo Campos', 'Levante UD', 'portero'),
  ('202', 'Toljan', 'Levante UD', 'defensa'),
  ('203', 'Dela', 'Levante UD', 'defensa'),
  ('204', 'Elgezabal', 'Levante UD', 'defensa'),
  ('205', null, 'Levante UD', null),
  ('206', 'Manu Sánchez', 'Levante UD', 'defensa'),
  ('207', 'Oriol Rey', 'Levante UD', 'medio'),
  ('208', 'Arriaga', 'Levante UD', 'medio'),
  ('209', null, 'Levante UD', null),
  ('210', null, 'Levante UD', null),
  ('211', 'Carlos Álvarez', 'Levante UD', 'medio'),
  ('212', 'Tunde', 'Levante UD', 'delantero'),
  ('213', 'Brugué', 'Levante UD', 'delantero'),
  ('214', 'Iván Romero', 'Levante UD', 'delantero'),
  ('215', 'Carlos Espí', 'Levante UD', 'delantero'),
  ('216', 'Etta Eyong', 'Levante UD', 'delantero'),
  ('217', 'Escudo', 'Real Madrid CF', null),
  ('218', 'Courtois', 'Real Madrid CF', 'portero'),
  ('219', 'Lunin', 'Real Madrid CF', 'portero'),
  ('220', 'Trent', 'Real Madrid CF', 'defensa'),
  ('221', 'Militao', 'Real Madrid CF', 'defensa'),
  ('222', 'Huijsen', 'Real Madrid CF', 'defensa'),
  ('223', 'Rüdiger', 'Real Madrid CF', 'defensa'),
  ('224', 'Carreras', 'Real Madrid CF', 'defensa'),
  ('225', 'Tchouaméni', 'Real Madrid CF', 'medio'),
  ('226', 'Fede Valverde', 'Real Madrid CF', 'medio'),
  ('227', 'Camavinga', 'Real Madrid CF', 'medio'),
  ('228', 'Bellingham', 'Real Madrid CF', 'medio'),
  ('229', 'Güler', 'Real Madrid CF', 'medio'),
  ('230', 'Brahim Díaz', 'Real Madrid CF', 'delantero'),
  ('231', 'Rodrygo', 'Real Madrid CF', 'delantero'),
  ('232', 'Mbappé', 'Real Madrid CF', 'delantero'),
  ('233', 'Gonzalo', 'Real Madrid CF', 'delantero'),
  ('234', 'Vinícius', 'Real Madrid CF', 'delantero'),
  ('235', 'Escudo', 'Málaga CF', null),
  ('236', 'Alfonso Herrero', 'Málaga CF', 'portero'),
  ('237', 'Carlos López', 'Málaga CF', 'portero'),
  ('238', 'Puga', 'Málaga CF', 'defensa'),
  ('239', 'Murillo', 'Málaga CF', 'defensa'),
  ('240', null, 'Málaga CF', null),
  ('241', 'Einar Galilea', 'Málaga CF', 'defensa'),
  ('242', 'Rafita', 'Málaga CF', 'defensa'),
  ('243', null, 'Málaga CF', null),
  ('244', 'Izan Mérino', 'Málaga CF', 'medio'),
  ('245', 'Dani Lorenzo', 'Málaga CF', 'medio'),
  ('246', 'Rafa Rodríguez', 'Málaga CF', 'medio'),
  ('247', 'Dotor', 'Málaga CF', 'medio'),
  ('248', 'Larrubia', 'Málaga CF', 'delantero'),
  ('249', 'Lobete', 'Málaga CF', 'delantero'),
  ('250', 'Adrián Niño', 'Málaga CF', 'delantero'),
  ('251', 'Joaquín', 'Málaga CF', 'delantero'),
  ('252', 'Chupe', 'Málaga CF', 'delantero'),
  ('253', 'Escudo', 'Osasuna', null),
  ('254', 'Sergio Herrera', 'Osasuna', 'portero'),
  ('255', 'Aitor Fernández', 'Osasuna', 'portero'),
  ('256', 'Rosier', 'Osasuna', 'defensa'),
  ('257', 'Boyomo', 'Osasuna', 'defensa'),
  ('258', 'Catena', 'Osasuna', 'defensa'),
  ('259', 'Herrando', 'Osasuna', 'defensa'),
  ('260', 'Abel Bretones', 'Osasuna', 'defensa'),
  ('261', 'Iker Muñoz', 'Osasuna', 'medio'),
  ('262', 'Torró', 'Osasuna', 'medio'),
  ('263', 'Moncayola', 'Osasuna', 'medio'),
  ('264', 'Moi Gómez', 'Osasuna', 'medio'),
  ('265', 'Rubén García', 'Osasuna', 'medio'),
  ('266', 'Aimar Oroz', 'Osasuna', 'medio'),
  ('267', 'Raúl Moro', 'Osasuna', 'delantero'),
  ('268', 'Kike Barja', 'Osasuna', 'delantero'),
  ('269', 'Raúl García', 'Osasuna', 'delantero'),
  ('270', 'Budimir', 'Osasuna', 'delantero'),
  ('271', 'Escudo', 'Racing de Santander', null),
  ('272', null, 'Racing de Santander', null),
  ('273', 'Eriksson', 'Racing de Santander', 'portero'),
  ('274', 'Mantilla', 'Racing de Santander', 'defensa'),
  ('275', 'Sangalli', 'Racing de Santander', 'defensa'),
  ('276', 'Facu González', 'Racing de Santander', 'defensa'),
  ('277', 'Javi Castro', 'Racing de Santander', 'defensa'),
  ('278', 'Manu Hernando', 'Racing de Santander', 'defensa'),
  ('279', 'Jorge Salinas', 'Racing de Santander', 'defensa'),
  ('280', 'Maguette', 'Racing de Santander', 'medio'),
  ('281', 'Gustavo Puerta', 'Racing de Santander', 'medio'),
  ('282', 'Íñigo', 'Racing de Santander', 'medio'),
  ('283', 'Aldasoro', 'Racing de Santander', 'medio'),
  ('284', 'Suleiman', 'Racing de Santander', 'delantero'),
  ('285', 'Andrés Martín', 'Racing de Santander', 'delantero'),
  ('286', 'Guliashvili', 'Racing de Santander', 'delantero'),
  ('287', 'Villalibre', 'Racing de Santander', 'delantero'),
  ('288', 'Íñigo Vicente', 'Racing de Santander', 'delantero'),
  ('289', 'Escudo', 'Rayo Vallecano', null),
  ('290', 'Batalla', 'Rayo Vallecano', 'portero'),
  ('291', 'Cárdenas', 'Rayo Vallecano', 'portero'),
  ('292', 'Ratiu', 'Rayo Vallecano', 'defensa'),
  ('293', 'Balliu', 'Rayo Vallecano', 'defensa'),
  ('294', 'Lejeune', 'Rayo Vallecano', 'defensa'),
  ('295', 'Nobel Mendy', 'Rayo Vallecano', 'defensa'),
  ('296', 'Luiz Felipe', 'Rayo Vallecano', 'defensa'),
  ('297', 'Pep Chavarría', 'Rayo Vallecano', 'defensa'),
  ('298', 'Pedro Díaz', 'Rayo Vallecano', 'medio'),
  ('299', 'Pathé Ciss', 'Rayo Vallecano', 'medio'),
  ('300', 'Óscar Valentín', 'Rayo Vallecano', 'medio'),
  ('301', 'Unai López', 'Rayo Vallecano', 'medio'),
  ('302', 'Isi', 'Rayo Vallecano', 'medio'),
  ('303', 'Álvaro García', 'Rayo Vallecano', 'delantero'),
  ('304', 'De Frutos', 'Rayo Vallecano', 'delantero'),
  ('305', 'Camello', 'Rayo Vallecano', 'delantero'),
  ('306', 'Alemao', 'Rayo Vallecano', 'delantero'),
  ('307', 'Escudo', 'Real Sociedad', null),
  ('308', 'Remiro', 'Real Sociedad', 'portero'),
  ('309', 'Marrero', 'Real Sociedad', 'portero'),
  ('310', 'Aramburu', 'Real Sociedad', 'defensa'),
  ('311', 'Jon Martín', 'Real Sociedad', 'defensa'),
  ('312', 'Zubeldia', 'Real Sociedad', 'defensa'),
  ('313', 'Sergio Gómez', 'Real Sociedad', 'defensa'),
  ('314', 'Aihen Muñoz', 'Real Sociedad', 'defensa'),
  ('315', 'Gorrotxategi', 'Real Sociedad', 'medio'),
  ('316', 'Turrientes', 'Real Sociedad', 'medio'),
  ('317', 'Pablo Marín', 'Real Sociedad', 'medio'),
  ('318', null, 'Real Sociedad', null),
  ('319', 'Carlos Soler', 'Real Sociedad', 'medio'),
  ('320', 'Sucic', 'Real Sociedad', 'medio'),
  ('321', 'Barrenetxea', 'Real Sociedad', 'delantero'),
  ('322', 'Guedes', 'Real Sociedad', 'delantero'),
  ('323', 'Kubo', 'Real Sociedad', 'delantero'),
  ('324', 'Oyarzabal', 'Real Sociedad', 'delantero'),
  ('325', 'Escudo', 'Sevilla', null),
  ('326', 'Vlachodimos', 'Sevilla', 'portero'),
  ('327', null, 'Sevilla', null),
  ('328', 'Carmona', 'Sevilla', 'defensa'),
  ('329', 'Juanlu', 'Sevilla', 'defensa'),
  ('330', 'Kike Salas', 'Sevilla', 'defensa'),
  ('331', 'Nianzou', 'Sevilla', 'defensa'),
  ('332', 'Castrín', 'Sevilla', 'defensa'),
  ('333', 'Suazo', 'Sevilla', 'defensa'),
  ('334', 'Oso', 'Sevilla', 'medio'),
  ('335', 'Agoumé', 'Sevilla', 'medio'),
  ('336', 'Sow', 'Sevilla', 'medio'),
  ('337', 'Vargas', 'Sevilla', 'medio'),
  ('338', null, 'Sevilla', null),
  ('339', 'Peque', 'Sevilla', 'delantero'),
  ('340', 'Ejuke', 'Sevilla', 'delantero'),
  ('341', 'Akor Adams', 'Sevilla', 'delantero'),
  ('342', 'Isaac Romero', 'Sevilla', 'delantero'),
  ('343', 'Escudo', 'Valencia', null),
  ('344', 'Dimitrievski', 'Valencia', 'portero'),
  ('345', 'Rivero', 'Valencia', 'portero'),
  ('346', 'Foulquier', 'Valencia', 'defensa'),
  ('347', 'Diakhaby', 'Valencia', 'defensa'),
  ('348', 'Tárrega', 'Valencia', 'defensa'),
  ('349', 'Copete', 'Valencia', 'defensa'),
  ('350', 'Cömert', 'Valencia', 'defensa'),
  ('351', 'Gayà', 'Valencia', 'defensa'),
  ('352', 'Pepelu', 'Valencia', 'medio'),
  ('353', 'Guido Rodríguez', 'Valencia', 'medio'),
  ('354', 'Javi Guerra', 'Valencia', 'medio'),
  ('355', 'Luis Rioja', 'Valencia', 'medio'),
  ('356', null, 'Valencia', null),
  ('357', 'Ramazani', 'Valencia', 'delantero'),
  ('358', 'Hugo Duro', 'Valencia', 'delantero'),
  ('359', 'Diego López', 'Valencia', 'delantero'),
  ('360', 'Sadiq', 'Valencia', 'delantero'),
  ('361', 'Escudo', 'Villarreal', null),
  ('362', 'Luiz Júnior', 'Villarreal', 'portero'),
  ('363', 'Arnau Tenas', 'Villarreal', 'portero'),
  ('364', 'Mouriño', 'Villarreal', 'defensa'),
  ('365', 'Pau Navarro', 'Villarreal', 'defensa'),
  ('366', 'Foyth', 'Villarreal', 'defensa'),
  ('367', null, 'Villarreal', null),
  ('368', 'Renato Veiga', 'Villarreal', 'defensa'),
  ('369', 'Sergi Cardona', 'Villarreal', 'defensa'),
  ('370', 'Santi Comesaña', 'Villarreal', 'medio'),
  ('371', 'Maciá', 'Villarreal', 'medio'),
  ('372', 'Pape Gueye', 'Villarreal', 'medio'),
  ('373', 'Moleiro', 'Villarreal', 'medio'),
  ('374', 'Buchanan', 'Villarreal', 'delantero'),
  ('375', 'Pépé', 'Villarreal', 'delantero'),
  ('376', 'Mikautadze', 'Villarreal', 'delantero'),
  ('377', 'Ayoze', 'Villarreal', 'delantero'),
  ('378', 'Gerard Moreno', 'Villarreal', 'delantero'),
  ('379', 'Abde Betis', 'Enjoy', 'enjoy'),
  ('380', 'Brahim Díaz Real Madrid', 'Enjoy', 'enjoy'),
  ('381', 'Dani Olmo Barcelona', 'Enjoy', 'enjoy'),
  ('382', 'Dolan Espanyol', 'Enjoy', 'enjoy'),
  ('383', 'Íñigo Vicente Racing', 'Enjoy', 'enjoy'),
  ('384', 'Kubo Real Sociedad', 'Enjoy', 'enjoy'),
  ('385', 'Lookman Atlético', 'Enjoy', 'enjoy'),
  ('386', 'Pépé Villarreal', 'Enjoy', 'enjoy'),
  ('387', 'Vargas Sevilla', 'Enjoy', 'enjoy'),
  ('379P', 'Abde Betis', 'Enjoy Power', 'enjoy power'),
  ('380P', 'Brahim Díaz Real Madrid', 'Enjoy Power', 'enjoy power'),
  ('381P', 'Dani Olmo Barcelona', 'Enjoy Power', 'enjoy power'),
  ('382P', 'Dolan Espanyol', 'Enjoy Power', 'enjoy power'),
  ('383P', 'Íñigo Vicente Racing', 'Enjoy Power', 'enjoy power'),
  ('384P', 'Kubo Real Sociedad', 'Enjoy Power', 'enjoy power'),
  ('385P', 'Lookman Atlético', 'Enjoy Power', 'enjoy power'),
  ('386P', 'Pépé Villarreal', 'Enjoy Power', 'enjoy power'),
  ('387P', 'Vargas Sevilla', 'Enjoy Power', 'enjoy power'),
  ('388', 'Antony Betis', 'Zona VIP', 'zona vip'),
  ('389', 'Borja Iglesias Celta', 'Zona VIP', 'zona vip'),
  ('390', 'Carlos Soler Real Sociedad', 'Zona VIP', 'zona vip'),
  ('391', 'Cubarsí Barcelona', 'Zona VIP', 'zona vip'),
  ('392', 'De Frutos Rayo Vallecano', 'Zona VIP', 'zona vip'),
  ('393', 'Eric García Barcelona', 'Zona VIP', 'zona vip'),
  ('394', 'Gavi Barcelona', 'Zona VIP', 'zona vip'),
  ('395', 'Guedes Real Sociedad', 'Zona VIP', 'zona vip'),
  ('396', 'Güler Real Madrid', 'Zona VIP', 'zona vip'),
  ('397', 'Hancko Atlético', 'Zona VIP', 'zona vip'),
  ('398', 'Jauregizar Athletic', 'Zona VIP', 'zona vip'),
  ('399', 'Joan García Barcelona', 'Zona VIP', 'zona vip'),
  ('400', 'Koke Atlético', 'Zona VIP', 'zona vip'),
  ('401', 'Marcos Llorente Atlético', 'Zona VIP', 'zona vip'),
  ('402', 'Mikautadze Villarreal', 'Zona VIP', 'zona vip'),
  ('403', 'Oblak Atlético', 'Zona VIP', 'zona vip'),
  ('404', 'Pubill Atlético', 'Zona VIP', 'zona vip'),
  ('405', 'Tchouaméni Real Madrid', 'Zona VIP', 'zona vip'),
  ('388P', 'Antony Betis', 'Zona VIP Power', 'zona vip power'),
  ('389P', 'Borja Iglesias Celta', 'Zona VIP Power', 'zona vip power'),
  ('390P', 'Carlos Soler Real Sociedad', 'Zona VIP Power', 'zona vip power'),
  ('391P', 'Cubarsí Barcelona', 'Zona VIP Power', 'zona vip power'),
  ('392P', 'De Frutos Rayo', 'Zona VIP Power', 'zona vip power'),
  ('393P', 'Eric García Barcelona', 'Zona VIP Power', 'zona vip power'),
  ('394P', 'Gavi Barcelona', 'Zona VIP Power', 'zona vip power'),
  ('395P', 'Guedes Real Sociedad', 'Zona VIP Power', 'zona vip power'),
  ('396P', 'Güler Real Madrid', 'Zona VIP Power', 'zona vip power'),
  ('397P', 'Hancko Atlético', 'Zona VIP Power', 'zona vip power'),
  ('398P', 'Jauregizar Athletic', 'Zona VIP Power', 'zona vip power'),
  ('399P', 'Joan García Barcelona', 'Zona VIP Power', 'zona vip power'),
  ('400P', 'Koke Atlético', 'Zona VIP Power', 'zona vip power'),
  ('401P', 'Marcos Llorente Atlético', 'Zona VIP Power', 'zona vip power'),
  ('402P', 'Mikautadze Villarreal', 'Zona VIP Power', 'zona vip power'),
  ('403P', 'Oblak Atlético', 'Zona VIP Power', 'zona vip power'),
  ('404P', 'Pubill Atlético', 'Zona VIP Power', 'zona vip power'),
  ('405P', 'Tchouaméni Real Madrid', 'Zona VIP Power', 'zona vip power'),
  ('406', 'Abdelkarim Barcelona', 'Master Rookie', 'master rookie'),
  ('407', 'Antañón Celta', 'Master Rookie', 'master rookie'),
  ('408', 'Carlos Espí Levante', 'Master Rookie', 'master rookie'),
  ('409', 'Chupe Malaga', 'Master Rookie', 'master rookie'),
  ('410', 'Cubo Atlético', 'Master Rookie', 'master rookie'),
  ('411', 'Dani Díaz Real Sociedad', 'Master Rookie', 'master rookie'),
  ('412', 'Hugo López Villarreal', 'Master Rookie', 'master rookie'),
  ('413', 'Joan Martínez Real Madrid', 'Master Rookie', 'master rookie'),
  ('414', 'Jorge Salinas Racing', 'Master Rookie', 'master rookie'),
  ('415', 'Julio Díaz Atlético', 'Master Rookie', 'master rookie'),
  ('416', 'Lamini Fati Real Madrid', 'Master Rookie', 'master rookie'),
  ('417', 'Maciá Villarreal', 'Master Rookie', 'master rookie'),
  ('418', 'Rego Athletic', 'Master Rookie', 'master rookie'),
  ('419', 'Thiago Pitarch Real Madrid', 'Master Rookie', 'master rookie'),
  ('420', 'Tommy Marqués Barcelona', 'Master Rookie', 'master rookie'),
  ('421', 'Tunde Levante', 'Master Rookie', 'master rookie'),
  ('422', 'Xavi Espart Barcelona', 'Master Rookie', 'master rookie'),
  ('423', 'Yeremay Deportivo', 'Master Rookie', 'master rookie'),
  ('424', 'Logo con dos portadas', 'Stars On 25', 'stars on 25'),
  ('425', 'Collage 7 jugadores', 'Stars On 25', 'stars on 25'),
  ('426', 'Raúl Real Madrid', 'Stars On 25', 'stars on 25'),
  ('427', 'Xavi Barcelona', 'Stars On 25', 'stars on 25'),
  ('428', 'Casillas Real Madrid', 'Stars On 25', 'stars on 25'),
  ('429', 'Puyol Barcelona', 'Stars On 25', 'stars on 25'),
  ('430', 'Zidane Real Madrid', 'Stars On 25', 'stars on 25'),
  ('431', 'Joaquín Betis', 'Stars On 25', 'stars on 25'),
  ('432', 'Fernando Torres Atlético', 'Stars On 25', 'stars on 25'),
  ('433', 'Aduriz Athletic', 'Stars On 25', 'stars on 25'),
  ('434', 'Iniesta Barcelona', 'Stars On 25', 'stars on 25'),
  ('435', 'Villa Valencia', 'Stars On 25', 'stars on 25'),
  ('436', 'Ronaldinho Barcelona', 'Stars On 25', 'stars on 25'),
  ('437', 'Jesús Navas Sevilla', 'Stars On 25', 'stars on 25'),
  ('438', 'Cazorla Villarreal', 'Stars On 25', 'stars on 25'),
  ('439', 'Forlán Atlético', 'Stars On 25', 'stars on 25'),
  ('440', 'Messi Barcelona', 'Stars On 25', 'stars on 25'),
  ('441', 'Benzema Real Madrid', 'Stars On 25', 'stars on 25'),
  ('442', 'Cristiano Ronaldo Real Madrid', 'Stars On 25', 'stars on 25'),
  ('443', 'Griezmann Atlético', 'Stars On 25', 'stars on 25'),
  ('444', 'Iago Aspas Celta', 'Stars On 25', 'stars on 25'),
  ('445', 'Modric Real Madrid', 'Stars On 25', 'stars on 25'),
  ('446', 'Neymar Barcelona', 'Stars On 25', 'stars on 25'),
  ('447', 'Oblak Atlético', 'Stars On 25', 'stars on 25'),
  ('448', 'Oyarzabal Real Sociedad', 'Stars On 25', 'stars on 25'),
  ('449', 'Lamine Yamal Barcelona', 'Stars On 25', 'stars on 25'),
  ('450', 'Mbappé Real Madrid', 'Stars On 25', 'stars on 25'),
  ('25u-CR7', 'Cristiano Ronaldo · Real Madrid', 'Just 25', 'just 25'),
  ('25u-MESSI', 'Messi · Barcelona', 'Just 25', 'just 25'),
  ('AUT-01', 'Antonio Sivera · Deportivo Alavés', 'Autógrafos', '/200'),
  ('AUT-02', 'Aitor Paredes · Athletic', 'Autógrafos', '/200'),
  ('AUT-03', 'Pablo García · Betis', 'Autógrafos', '/200'),
  ('AUT-04', 'Aleix Febas · Celta', 'Autógrafos', '/200'),
  ('AUT-05', 'Javi Guerra · Valencia', 'Autógrafos', '/200'),
  ('AUT-06', 'Roberto Fernández · Espanyol', 'Autógrafos', '/200'),
  ('AUT-07', 'David Soria · Getafe', 'Autógrafos', '/200'),
  ('AUT-08', 'Kike Salas · Sevilla', 'Autógrafos', '/200'),
  ('AUT-09', 'Carlos Soler · Real Sociedad', 'Autógrafos', '/100'),
  ('AUT-10', 'Augusto Batalla · Rayo Vallecano', 'Autógrafos', '/100'),
  ('AUT-11', 'Tajon Buchanan · Villarreal', 'Autógrafos', '/100'),
  ('AUT-12', 'Marc Pubill · Atlético de Madrid', 'Autógrafos', '/100'),
  ('AUT-13', 'Unai Gómez · Athletic', 'Autógrafos', '/100'),
  ('AUT-14', 'Antonio Blanco · Alavés', 'Autógrafos', '/100'),
  ('AUT-15', 'Giuliano Simeone · Atlético de Madrid', 'Autógrafos', '/50'),
  ('AUT-16', 'Iñaki Williams · Athletic', 'Autógrafos', '/50'),
  ('AUT-17', 'Víctor Muñoz · Osasuna', 'Autógrafos', '/50'),
  ('AUT-18', 'Gerard Martín · Barcelona', 'Autógrafos', '/50'),
  ('AUT-19', 'Thiago Pitarch / Arda Güler · Real Madrid', 'Autógrafos', 'doble /50'),
  ('AUT-20', 'Alberto Moleiro / Gerard Moreno · Villarreal', 'Autógrafos', 'doble /50'),
  ('AUT-21', 'Pedri González · Barcelona', 'Autógrafos', '/5'),
  ('AUT-22', 'Julián Alvarez · Atlético de Madrid', 'Autógrafos', '/5')
) as v(number, name, team, category)
where c.slug = 'megacracks-2026-27'
on conflict (collection_id, number, team) do update
set name=excluded.name, category=excluded.category;
