-- Catálogo extraído del checklist oficial LaLiga ESTE 2026/27.
insert into public.collections (slug, name, season, publisher, total_stickers, is_active)
values ('laliga-este-2026-27', 'LaLiga ESTE 2026/27', '2026/27', 'Panini', 514, true)
on conflict (slug) do update set total_stickers = excluded.total_stickers, is_active = true;

insert into public.stickers (collection_id, number, name, team, category)
select c.id, v.number, v.name, v.team, v.category
from public.collections c
cross join (values
  ('1', 'Escudo', 'Deportivo Alavés', null),
  ('2', 'Quique Sánchez Flores', 'Deportivo Alavés', 'entrenador'),
  ('3', 'Sivera', 'Deportivo Alavés', 'portero'),
  ('4', null, 'Deportivo Alavés', null),
  ('5', 'Jonny', 'Deportivo Alavés', 'defensa'),
  ('6', 'Koski', 'Deportivo Alavés', 'defensa'),
  ('7', 'Tenaglia', 'Deportivo Alavés', 'defensa'),
  ('8', 'Parada', 'Deportivo Alavés', 'defensa'),
  ('9', 'Yusi', 'Deportivo Alavés', 'defensa'),
  ('10', null, 'Deportivo Alavés', null),
  ('11', 'Benavidez', 'Deportivo Alavés', 'medio'),
  ('12', 'Blanco', 'Deportivo Alavés', 'medio'),
  ('13', 'Guevara', 'Deportivo Alavés', 'medio'),
  ('14', 'Aleñá', 'Deportivo Alavés', 'medio'),
  ('15', 'Pablo Ibáñez', 'Deportivo Alavés', 'medio'),
  ('16', 'Denis Suárez', 'Deportivo Alavés', 'medio'),
  ('17', 'Ángel Pérez', 'Deportivo Alavés', 'delantero'),
  ('18A', 'Abde', 'Deportivo Alavés', 'delantero'),
  ('18B', 'Mañas', 'Deportivo Alavés', 'delantero'),
  ('19', 'Toni Martínez', 'Deportivo Alavés', 'delantero'),
  ('20', 'Boyé', 'Deportivo Alavés', 'delantero'),
  ('1', 'Escudo', 'Athletic Club De Bilbao', null),
  ('2', 'Edin Terzic', 'Athletic Club De Bilbao', 'entrenador'),
  ('3', 'Unai Simón', 'Athletic Club De Bilbao', 'portero'),
  ('4', 'Padilla', 'Athletic Club De Bilbao', 'portero'),
  ('5', 'Areso', 'Athletic Club De Bilbao', 'defensa'),
  ('6A', 'Paredes', 'Athletic Club De Bilbao', 'defensa'),
  ('6B', 'Yeray', 'Athletic Club De Bilbao', 'defensa'),
  ('7', 'Vivian', 'Athletic Club De Bilbao', 'defensa'),
  ('8', 'Laporte', 'Athletic Club De Bilbao', 'defensa'),
  ('9A', 'Yuri', 'Athletic Club De Bilbao', 'defensa'),
  ('9B', 'Adama Boiro', 'Athletic Club De Bilbao', 'defensa'),
  ('10', 'Jauregizar', 'Athletic Club De Bilbao', 'medio'),
  ('11', 'Ruiz de Galarreta', 'Athletic Club De Bilbao', 'medio'),
  ('12', 'Rego', 'Athletic Club De Bilbao', 'medio'),
  ('13', 'Unai Gómez', 'Athletic Club De Bilbao', 'medio'),
  ('14', 'Sancet', 'Athletic Club De Bilbao', 'medio'),
  ('15', 'Nico Serrano', 'Athletic Club De Bilbao', 'medio'),
  ('16', 'Berenguer', 'Athletic Club De Bilbao', 'delantero'),
  ('17A', 'Robert Navarro', 'Athletic Club De Bilbao', 'delantero'),
  ('17B', 'Maroan', 'Athletic Club De Bilbao', 'delantero'),
  ('18', 'Nico Williams', 'Athletic Club De Bilbao', 'delantero'),
  ('19', 'Williams', 'Athletic Club De Bilbao', 'delantero'),
  ('20', 'Guruzeta', 'Athletic Club De Bilbao', null),
  ('1', 'Escudo', 'Atlético De Madrid', null),
  ('2', 'Cholo Simeone', 'Atlético De Madrid', 'entrenador'),
  ('3', 'Oblak', 'Atlético De Madrid', 'portero'),
  ('4', 'Musso', 'Atlético De Madrid', 'portero'),
  ('5', 'Marcos Llorente', 'Atlético De Madrid', 'defensa'),
  ('6', 'Nahuel Molina', 'Atlético De Madrid', 'defensa'),
  ('7', 'Pubill', 'Atlético De Madrid', 'defensa'),
  ('8A', 'Le Normand', 'Atlético De Madrid', 'defensa'),
  ('8B', 'Giménez', 'Atlético De Madrid', 'defensa'),
  ('9', 'Hancko', 'Atlético De Madrid', 'defensa'),
  ('10', 'Ruggeri', 'Atlético De Madrid', 'defensa'),
  ('11', 'Koke', 'Atlético De Madrid', 'medio'),
  ('12', 'Barrios', 'Atlético De Madrid', 'medio'),
  ('13', 'Johnny Cardoso', 'Atlético De Madrid', 'medio'),
  ('14A', 'Rodri Mendoza', 'Atlético De Madrid', 'medio'),
  ('14B', 'Obed Vargas', 'Atlético De Madrid', 'medio'),
  ('15', 'Álex Baena', 'Atlético De Madrid', 'medio'),
  ('16', 'Almada', 'Atlético De Madrid', 'medio'),
  ('17', 'Giuliano', 'Atlético De Madrid', 'delantero'),
  ('18', 'Lookman', 'Atlético De Madrid', 'delantero'),
  ('19', 'Sorloth', 'Atlético De Madrid', 'delantero'),
  ('20', 'Julián Alvarez', 'Atlético De Madrid', 'delantero'),
  ('1', 'Escudo', 'Fc Barcelona', null),
  ('2', 'Hansi Flick', 'Fc Barcelona', 'entrenador'),
  ('3', 'Joan García', 'Fc Barcelona', 'portero'),
  ('4', 'Szczesny', 'Fc Barcelona', 'portero'),
  ('5', 'Koundé', 'Fc Barcelona', 'defensa'),
  ('6A', 'Araujo', 'Fc Barcelona', 'defensa'),
  ('6B', 'Christensen', 'Fc Barcelona', 'defensa'),
  ('7', 'Cubarsí', 'Fc Barcelona', 'defensa'),
  ('8', 'Gerard Martín', 'Fc Barcelona', 'defensa'),
  ('9', 'Joao Cancelo', 'Fc Barcelona', 'defensa'),
  ('10', 'Balde', 'Fc Barcelona', 'defensa'),
  ('11', 'Eric García', 'Fc Barcelona', 'defensa'),
  ('12', 'De Jong', 'Fc Barcelona', 'medio'),
  ('13', 'Gavi', 'Fc Barcelona', 'medio'),
  ('14', 'Bernal', 'Fc Barcelona', 'medio'),
  ('15', 'Pedri', 'Fc Barcelona', 'medio'),
  ('16', 'Fermín', 'Fc Barcelona', 'medio'),
  ('17', 'Dani Olmo', 'Fc Barcelona', 'delantero'),
  ('18', 'Ferran Torres', 'Fc Barcelona', 'delantero'),
  ('19', 'Raphinha', 'Fc Barcelona', 'delantero'),
  ('20', 'Lamine Yamal', 'Fc Barcelona', 'delantero'),
  ('1', 'Escudo', 'Real Betis', null),
  ('2', 'Manuel Pellegrini', 'Real Betis', 'entrenador'),
  ('3', 'Valles', 'Real Betis', 'portero'),
  ('4', 'Pau López', 'Real Betis', 'portero'),
  ('5A', 'Aitor Ruibal', 'Real Betis', 'defensa'),
  ('5B', 'Bellerín', 'Real Betis', 'defensa'),
  ('6', 'Diego Llorente', 'Real Betis', 'defensa'),
  ('7', 'Bartra', 'Real Betis', 'defensa'),
  ('8', 'Natan', 'Real Betis', 'defensa'),
  ('9', 'Valentín Gómez', 'Real Betis', 'defensa'),
  ('10', 'Marc Roca', 'Real Betis', 'medio'),
  ('11', 'Amrabat', 'Real Betis', 'medio'),
  ('12', 'Fidalgo', 'Real Betis', 'medio'),
  ('13', null, 'Real Betis', null),
  ('14', 'Lo Celso', 'Real Betis', 'medio'),
  ('15', 'Pablo Fornals', 'Real Betis', 'medio'),
  ('16', 'Isco', 'Real Betis', 'medio'),
  ('17', 'Riquelme', 'Real Betis', 'delantero'),
  ('18', 'Antony', 'Real Betis', 'delantero'),
  ('19', 'Cucho Hernández', 'Real Betis', 'delantero'),
  ('20', 'Abde', 'Real Betis', 'delantero'),
  ('1', 'Escudo', 'Rc Celta De Vigo', null),
  ('2', 'Claudio Giráldez', 'Rc Celta De Vigo', 'entrenador'),
  ('3', 'Radu', 'Rc Celta De Vigo', 'portero'),
  ('4', 'Iván Villar', 'Rc Celta De Vigo', 'portero'),
  ('5', 'Álvaro Núñez', 'Rc Celta De Vigo', 'defensa'),
  ('6', 'Javi Rueda', 'Rc Celta De Vigo', 'defensa'),
  ('7', 'Javi Rodríguez', 'Rc Celta De Vigo', 'defensa'),
  ('8', 'Starfelt', 'Rc Celta De Vigo', 'defensa'),
  ('9A', 'Marcos Alonso', 'Rc Celta De Vigo', 'defensa'),
  ('9B', 'Yoel Lago', 'Rc Celta De Vigo', 'defensa'),
  ('10', 'Carreira', 'Rc Celta De Vigo', 'defensa'),
  ('11', 'Ilaix Moriba', 'Rc Celta De Vigo', 'medio'),
  ('12', 'Miguel Román', 'Rc Celta De Vigo', 'medio'),
  ('13', 'Hugo Álvarez', 'Rc Celta De Vigo', 'medio'),
  ('14', 'Sotelo', 'Rc Celta De Vigo', 'medio'),
  ('15', 'Fer López', 'Rc Celta De Vigo', 'medio'),
  ('16', 'Swedberg', 'Rc Celta De Vigo', 'medio'),
  ('17', 'Iago Aspas', 'Rc Celta De Vigo', 'delantero'),
  ('18A', 'Pablo Durán', 'Rc Celta De Vigo', 'delantero'),
  ('18B', 'El-Abdellaoui', 'Rc Celta De Vigo', 'delantero'),
  ('19', 'Jutglà', 'Rc Celta De Vigo', 'delantero'),
  ('20', 'Borja Iglesias', 'Rc Celta De Vigo', 'delantero'),
  ('1', 'Escudo', 'Deportivo', null),
  ('2', 'Antonio Hidalgo', 'Deportivo', 'entrenador'),
  ('3', 'Álvaro Fernández', 'Deportivo', 'portero'),
  ('4', 'Germán Parreño', 'Deportivo', 'portero'),
  ('5', 'Adrià Altimira', 'Deportivo', 'defensa'),
  ('6', 'Loureiro', 'Deportivo', 'defensa'),
  ('7', 'Noubi', 'Deportivo', 'defensa'),
  ('8', 'Dani Barcia', 'Deportivo', 'defensa'),
  ('9A', 'Ximo Navarro', 'Deportivo', 'defensa'),
  ('9B', 'Arnau Comas', 'Deportivo', 'defensa'),
  ('10', 'Quagliata', 'Deportivo', 'defensa'),
  ('11', 'Villares', 'Deportivo', 'medio'),
  ('12', 'Riki', 'Deportivo', 'medio'),
  ('13', 'Mario Soriano', 'Deportivo', 'medio'),
  ('14', 'José Ángel', 'Deportivo', 'medio'),
  ('15', 'Luismi Cruz', 'Deportivo', 'medio'),
  ('16', 'Mella', 'Deportivo', 'medio'),
  ('17', null, 'Deportivo', null),
  ('18', 'Yeremay', 'Deportivo', 'delantero'),
  ('19', 'Eddahchouri', 'Deportivo', 'delantero'),
  ('20', 'Nsongo', 'Deportivo', 'delantero'),
  ('1', 'Escudo', 'Elche Cf', null),
  ('2', 'Eder Saravia', 'Elche Cf', 'entrenador'),
  ('3', 'Dituro', 'Elche Cf', 'portero'),
  ('4', null, 'Elche Cf', null),
  ('5', 'Pétrot', 'Elche Cf', 'defensa'),
  ('6', 'Chust', 'Elche Cf', 'defensa'),
  ('7', 'Bigas', 'Elche Cf', 'defensa'),
  ('8', 'Affengruber', 'Elche Cf', 'defensa'),
  ('9A', 'Pedrosa', 'Elche Cf', 'defensa'),
  ('9B', 'Sangaré', 'Elche Cf', 'defensa'),
  ('10', 'Germán Valera', 'Elche Cf', 'medio'),
  ('11', 'Martim Neto', 'Elche Cf', 'medio'),
  ('12', 'Gonzalo Villar', 'Elche Cf', 'medio'),
  ('13A', 'Fede Redondo', 'Elche Cf', 'medio'),
  ('13B', 'Jon Chetauya', 'Elche Cf', 'medio'),
  ('14', 'Marc Aguado', 'Elche Cf', 'medio'),
  ('15', 'Josan', 'Elche Cf', 'medio'),
  ('16', 'Morente', 'Elche Cf', 'medio'),
  ('17', null, 'Elche Cf', null),
  ('18', 'Cepeda', 'Elche Cf', 'delantero'),
  ('19', 'Diangana', 'Elche Cf', 'delantero'),
  ('20', 'Yago Santiago', 'Elche Cf', 'delantero'),
  ('1', 'Escudo', 'Rcd Espanyol', null),
  ('2', 'Manolo González', 'Rcd Espanyol', 'entrenador'),
  ('3', 'Dmitrovic', 'Rcd Espanyol', 'portero'),
  ('4', 'Fortuño', 'Rcd Espanyol', 'portero'),
  ('5', 'El Hilali', 'Rcd Espanyol', 'defensa'),
  ('6', 'Rubén Sánchez', 'Rcd Espanyol', 'defensa'),
  ('7', 'Riedel', 'Rcd Espanyol', 'defensa'),
  ('8', 'Cabrera', 'Rcd Espanyol', 'defensa'),
  ('9', 'Miguel Rubio', 'Rcd Espanyol', 'defensa'),
  ('10', null, 'Rcd Espanyol', null),
  ('11', 'Pol Lozano', 'Rcd Espanyol', 'medio'),
  ('12', 'Urko', 'Rcd Espanyol', 'medio'),
  ('13', 'Edu Expósito', 'Rcd Espanyol', 'medio'),
  ('14', 'Jofre', 'Rcd Espanyol', 'medio'),
  ('15', null, 'Rcd Espanyol', null),
  ('16', 'Dolan', 'Rcd Espanyol', 'delantero'),
  ('17', 'Pere Milla', 'Rcd Espanyol', 'delantero'),
  ('18', 'Puado', 'Rcd Espanyol', 'delantero'),
  ('19', 'Kike García', 'Rcd Espanyol', 'delantero'),
  ('20', 'Roberto Fernández', 'Rcd Espanyol', 'delantero'),
  ('1', 'Escudo', 'Getafe Cf', null),
  ('2', 'Jose Bordalás', 'Getafe Cf', 'entrenador'),
  ('3', 'David Soria', 'Getafe Cf', 'portero'),
  ('4', 'Letacek', 'Getafe Cf', 'portero'),
  ('5', 'Kiko Femenía', 'Getafe Cf', 'defensa'),
  ('6', 'Djené', 'Getafe Cf', 'defensa'),
  ('7', 'Boselli', 'Getafe Cf', 'defensa'),
  ('8', 'Abqar', 'Getafe Cf', 'defensa'),
  ('9', 'Zaid Romero', 'Getafe Cf', 'defensa'),
  ('10', 'Davinchi', 'Getafe Cf', 'defensa'),
  ('11', 'Mario Martín', 'Getafe Cf', 'medio'),
  ('12', 'Javi Muñoz', 'Getafe Cf', 'medio'),
  ('13', null, 'Getafe Cf', null),
  ('14', null, 'Getafe Cf', null),
  ('15', null, 'Getafe Cf', null),
  ('16', null, 'Getafe Cf', null),
  ('17', 'Álex Sancris', 'Getafe Cf', 'delantero'),
  ('18', 'Borja Mayoral', 'Getafe Cf', 'delantero'),
  ('19', 'Luis Vázquez', 'Getafe Cf', 'delantero'),
  ('20', 'Satriano', 'Getafe Cf', 'delantero'),
  ('1', 'Escudo', 'Levante Ud', null),
  ('2', 'Luís Castro', 'Levante Ud', 'entrenador'),
  ('3', 'Ryan', 'Levante Ud', 'portero'),
  ('4', 'Pablo Campos', 'Levante Ud', 'portero'),
  ('5', 'Toljan', 'Levante Ud', 'defensa'),
  ('6', 'Elgezabal', 'Levante Ud', 'defensa'),
  ('7', 'Dela', 'Levante Ud', 'defensa'),
  ('8', null, 'Levante Ud', null),
  ('9', 'Manu Sánchez', 'Levante Ud', 'defensa'),
  ('10', 'Arriaga', 'Levante Ud', 'medio'),
  ('11', 'Oriol Rey', 'Levante Ud', 'medio'),
  ('12', 'Olasagasti', 'Levante Ud', 'medio'),
  ('13', null, 'Levante Ud', null),
  ('14A', 'Victor García', 'Levante Ud', 'medio'),
  ('14B', 'Paco Cortés', 'Levante Ud', 'medio'),
  ('15', 'Carlos Álvarez', 'Levante Ud', 'medio'),
  ('16', 'Tunde', 'Levante Ud', 'delantero'),
  ('17', 'Brugué', 'Levante Ud', 'delantero'),
  ('18', 'Iván Romero', 'Levante Ud', 'delantero'),
  ('19', 'Etta Eyong', 'Levante Ud', 'delantero'),
  ('20', 'Carlos Espí', 'Levante Ud', 'delantero'),
  ('1', 'Escudo', 'Real Madrid Cf', null),
  ('2', 'José Mourinho', 'Real Madrid Cf', 'entrenador'),
  ('3', 'Courtois', 'Real Madrid Cf', 'portero'),
  ('4', 'Lunin', 'Real Madrid Cf', 'portero'),
  ('5', 'Trent', 'Real Madrid Cf', 'defensa'),
  ('6', 'Militao', 'Real Madrid Cf', 'defensa'),
  ('7', 'Asencio', 'Real Madrid Cf', 'defensa'),
  ('8', 'Rüdiger', 'Real Madrid Cf', 'defensa'),
  ('9', 'Huijsen', 'Real Madrid Cf', 'defensa'),
  ('10A', 'Carreras', 'Real Madrid Cf', 'defensa'),
  ('10B', 'Mendy', 'Real Madrid Cf', 'defensa'),
  ('11', 'Tchouaméni', 'Real Madrid Cf', 'medio'),
  ('12', 'Fede Valverde', 'Real Madrid Cf', 'medio'),
  ('13', 'Camavinga', 'Real Madrid Cf', 'medio'),
  ('14', 'Bellingham', 'Real Madrid Cf', 'medio'),
  ('15A', 'Güler', 'Real Madrid Cf', 'medio'),
  ('15B', 'Thiago Pitarch', 'Real Madrid Cf', 'medio'),
  ('16A', 'Mastantuono', 'Real Madrid Cf', 'medio'),
  ('16B', 'Brahim Díaz', 'Real Madrid Cf', 'delantero'),
  ('17', 'Gonzalo', 'Real Madrid Cf', 'delantero'),
  ('18', 'Rodrygo', 'Real Madrid Cf', 'delantero'),
  ('19', 'Vinícius', 'Real Madrid Cf', 'delantero'),
  ('20', 'Mbappé', 'Real Madrid Cf', 'delantero'),
  ('1', 'Escudo', 'Malaga Cf', null),
  ('2', 'Juan Franisco Funes', 'Malaga Cf', 'entrenador'),
  ('3', 'Alfonso Herrero', 'Malaga Cf', 'portero'),
  ('4', 'Carlos López', 'Malaga Cf', 'portero'),
  ('5', 'Puga', 'Malaga Cf', 'defensa'),
  ('6', 'Murillo', 'Malaga Cf', 'defensa'),
  ('7', null, 'Malaga Cf', null),
  ('8', 'Einar Galilea', 'Malaga Cf', 'defensa'),
  ('9', 'Rafita', 'Malaga Cf', 'defensa'),
  ('10', null, 'Malaga Cf', null),
  ('11', 'Izan Mérino', 'Malaga Cf', 'medio'),
  ('12', 'Dani Lorenzo', 'Malaga Cf', 'medio'),
  ('13A', 'Rafa Rodríguez', 'Malaga Cf', 'medio'),
  ('13B', 'Juanpe', 'Malaga Cf', 'medio'),
  ('14', 'Dotor', 'Malaga Cf', 'medio'),
  ('15', 'Aarón Ochoa', 'Malaga Cf', 'medio'),
  ('16', 'Larrubia', 'Malaga Cf', 'delantero'),
  ('17', 'Lobete', 'Malaga Cf', 'delantero'),
  ('18', 'Adrián Niño', 'Malaga Cf', 'delantero'),
  ('19', 'Joaquín', 'Malaga Cf', 'delantero'),
  ('20', 'Chupe', 'Malaga Cf', 'delantero'),
  ('1', 'Escudo', 'Osasuna', null),
  ('2', 'Luis Miguel Ramis', 'Osasuna', 'entrenador'),
  ('3', 'Sergio Herrera', 'Osasuna', 'portero'),
  ('4', 'Aitor Fernández', 'Osasuna', 'portero'),
  ('5A', 'Rosier', 'Osasuna', 'defensa'),
  ('5B', 'Arguibide', 'Osasuna', 'defensa'),
  ('6', 'Boyomo', 'Osasuna', 'defensa'),
  ('7', 'Herrando', 'Osasuna', 'defensa'),
  ('8', 'Catena', 'Osasuna', 'defensa'),
  ('9', 'Abel Bretones', 'Osasuna', 'defensa'),
  ('10', 'Osambela', 'Osasuna', 'medio'),
  ('11', 'Torró', 'Osasuna', 'medio'),
  ('12', 'Moncayola', 'Osasuna', 'medio'),
  ('13A', 'Moi Gómez', 'Osasuna', 'medio'),
  ('13B', 'Iker Muñoz', 'Osasuna', 'medio'),
  ('14', 'Rubén García', 'Osasuna', 'medio'),
  ('15', 'Aimar Oroz', 'Osasuna', 'medio'),
  ('16', 'Iker Benito', 'Osasuna', 'medio'),
  ('17', 'Raúl Moro', 'Osasuna', 'delantero'),
  ('18', 'Raúl García', 'Osasuna', 'delantero'),
  ('19', 'Kike Barja', 'Osasuna', 'delantero'),
  ('20', 'Budimir', 'Osasuna', 'delantero'),
  ('1', 'Escudo', 'Racing De Santander', null),
  ('2', 'José Alberto López', 'Racing De Santander', 'entrenador'),
  ('3', null, 'Racing De Santander', null),
  ('4', 'Eriksson', 'Racing De Santander', 'portero'),
  ('5', 'Mantilla', 'Racing De Santander', 'defensa'),
  ('6', 'Sangalli', 'Racing De Santander', 'defensa'),
  ('7', 'Facu González', 'Racing De Santander', 'defensa'),
  ('8', 'Javi Castro', 'Racing De Santander', 'defensa'),
  ('9A', 'Manu Hernando', 'Racing De Santander', 'defensa'),
  ('9B', 'Mario García', 'Racing De Santander', 'defensa'),
  ('10', 'Jorge Salinas', 'Racing De Santander', 'defensa'),
  ('11A', 'Maguette', 'Racing De Santander', 'medio'),
  ('11B', 'Nteka', 'Racing De Santander', 'medio'),
  ('12', 'Gustavo Puerta', 'Racing De Santander', 'medio'),
  ('13', 'Íñigo', 'Racing De Santander', 'medio'),
  ('14', 'Aldasoro', 'Racing De Santander', 'medio'),
  ('15', 'Suleiman', 'Racing De Santander', 'delantero'),
  ('16', 'Andrés Martín', 'Racing De Santander', 'delantero'),
  ('17', 'Guliashvili', 'Racing De Santander', 'delantero'),
  ('18', 'Íñigo Vicente', 'Racing De Santander', 'delantero'),
  ('19', 'Arana', 'Racing De Santander', 'delantero'),
  ('20', 'Villalibre', 'Racing De Santander', 'delantero'),
  ('1', 'Escudo', 'Rayo Vallecano', null),
  ('2', 'Beñat San José', 'Rayo Vallecano', 'entrenador'),
  ('3', 'Batalla', 'Rayo Vallecano', 'portero'),
  ('4', 'Cárdenas', 'Rayo Vallecano', 'portero'),
  ('5', 'Ratiu', 'Rayo Vallecano', 'defensa'),
  ('6', 'Balliu', 'Rayo Vallecano', 'defensa'),
  ('7', 'Nobel Mendy', 'Rayo Vallecano', 'defensa'),
  ('8', 'Lejeune', 'Rayo Vallecano', 'defensa'),
  ('9', 'Luiz Felipe', 'Rayo Vallecano', 'defensa'),
  ('10', 'Pep Chavarría', 'Rayo Vallecano', 'defensa'),
  ('11', 'Pedro Díaz', 'Rayo Vallecano', 'medio'),
  ('12', 'Pathé Ciss', 'Rayo Vallecano', 'medio'),
  ('13', 'Óscar Valentín', 'Rayo Vallecano', 'medio'),
  ('14', 'Unai López', 'Rayo Vallecano', 'medio'),
  ('15', 'Isi', 'Rayo Vallecano', 'medio'),
  ('16', 'De Frutos', 'Rayo Vallecano', 'delantero'),
  ('17', 'Fran Pérez', 'Rayo Vallecano', 'delantero'),
  ('18', 'Álvaro García', 'Rayo Vallecano', 'delantero'),
  ('19', 'Camello', 'Rayo Vallecano', 'delantero'),
  ('20', 'Alemao', 'Rayo Vallecano', 'delantero'),
  ('1', 'Escudo', 'Real Sociedad', null),
  ('2', 'Pellegrino Matarazzo', 'Real Sociedad', 'entrenador'),
  ('3', 'Remiro', 'Real Sociedad', 'portero'),
  ('4', 'Marrero', 'Real Sociedad', 'portero'),
  ('5', 'Aramburu', 'Real Sociedad', 'defensa'),
  ('6', 'Zubeldia', 'Real Sociedad', 'defensa'),
  ('7', 'Jon Martín', 'Real Sociedad', 'defensa'),
  ('8', 'Sergio Gómez', 'Real Sociedad', 'defensa'),
  ('9', 'Aihen Muñoz', 'Real Sociedad', 'defensa'),
  ('10', 'Gorrotxategi', 'Real Sociedad', 'medio'),
  ('11', 'Pablo Marín', 'Real Sociedad', 'medio'),
  ('12', 'Turrientes', 'Real Sociedad', 'medio'),
  ('13A', 'Yangel Herrera', 'Real Sociedad', 'medio'),
  ('13B', null, 'Real Sociedad', null),
  ('14', 'Carlos Soler', 'Real Sociedad', 'medio'),
  ('15', 'Sucic', 'Real Sociedad', 'medio'),
  ('16', 'Barrenetxea', 'Real Sociedad', 'delantero'),
  ('17', 'Kubo', 'Real Sociedad', 'delantero'),
  ('18', 'Guedes', 'Real Sociedad', 'delantero'),
  ('19', 'Oskarsson', 'Real Sociedad', 'delantero'),
  ('20', 'Oyarzabal', 'Real Sociedad', 'delantero'),
  ('1', 'Escudo', 'Sevilla', null),
  ('2', 'Luis García', 'Sevilla', 'entrenador'),
  ('3', 'Vlachodimos', 'Sevilla', 'portero'),
  ('4', null, 'Sevilla', null),
  ('5', 'Carmona', 'Sevilla', 'defensa'),
  ('6', 'Juanlu', 'Sevilla', 'defensa'),
  ('7', 'Kike Salas', 'Sevilla', 'defensa'),
  ('8', 'Nianzou', 'Sevilla', 'defensa'),
  ('9A', 'Castrín', 'Sevilla', 'defensa'),
  ('9B', 'Marcao', 'Sevilla', 'defensa'),
  ('10', 'Suazo', 'Sevilla', 'defensa'),
  ('11', 'Oso', 'Sevilla', 'medio'),
  ('12', 'Agoumé', 'Sevilla', 'medio'),
  ('13', null, 'Sevilla', null),
  ('14', 'Sow', 'Sevilla', 'medio'),
  ('15', 'Vargas', 'Sevilla', 'medio'),
  ('16', 'Manu Bueno', 'Sevilla', 'medio'),
  ('17', 'Peque', 'Sevilla', 'delantero'),
  ('18', 'Ejuke', 'Sevilla', 'delantero'),
  ('19', 'Akor Adams', 'Sevilla', 'delantero'),
  ('20', 'Isaac Romero', 'Sevilla', 'delantero'),
  ('1', 'Escudo', 'Valencia', null),
  ('2', 'Carlos Corberán', 'Valencia', 'entrenador'),
  ('3', 'Dimitrievski', 'Valencia', 'portero'),
  ('4', 'Rivero', 'Valencia', 'portero'),
  ('5', 'Foulquier', 'Valencia', 'defensa'),
  ('6', 'Copete', 'Valencia', 'defensa'),
  ('7', 'Tárrega', 'Valencia', 'defensa'),
  ('8A', 'Cömert', 'Valencia', 'defensa'),
  ('8B', 'Diakhaby', 'Valencia', 'defensa'),
  ('9', 'Gayà', 'Valencia', 'defensa'),
  ('10', 'Jesús Vázquez', 'Valencia', 'defensa'),
  ('11', 'Pepelu', 'Valencia', 'medio'),
  ('12', 'Guido Rodríguez', 'Valencia', 'medio'),
  ('13', 'Javi Guerra', 'Valencia', 'medio'),
  ('14', 'Luis Rioja', 'Valencia', 'medio'),
  ('15', 'Ugrinic', 'Valencia', 'medio'),
  ('16', 'André Almeida', 'Valencia', 'medio'),
  ('17', 'Hugo Duro', 'Valencia', 'delantero'),
  ('18', 'Diego López', 'Valencia', 'delantero'),
  ('19', 'Ramazani', 'Valencia', 'delantero'),
  ('20A', 'Sadiq', 'Valencia', 'delantero'),
  ('20B', 'Lucas Beltrán', 'Valencia', 'delantero'),
  ('1', 'Escudo', 'Villarreal', null),
  ('2', 'Íñigo Pérez', 'Villarreal', 'entrenador'),
  ('3', 'Luiz Júnior', 'Villarreal', 'portero'),
  ('4', 'Arnau Tenas', 'Villarreal', 'portero'),
  ('5', 'Mouriño', 'Villarreal', 'defensa'),
  ('6A', 'Pau Navarro', 'Villarreal', 'defensa'),
  ('6B', 'Logan Costa', 'Villarreal', 'defensa'),
  ('7A', 'Foyth', 'Villarreal', 'defensa'),
  ('7B', 'Freeman', 'Villarreal', 'defensa'),
  ('8A', 'Kambwala', 'Villarreal', 'defensa'),
  ('8B', 'Rafa Marín', 'Villarreal', 'defensa'),
  ('9', 'Renato Veiga', 'Villarreal', 'defensa'),
  ('10', 'Sergi Cardona', 'Villarreal', 'defensa'),
  ('11', 'Pape Gueye', 'Villarreal', 'medio'),
  ('12', 'Santi Comesaña', 'Villarreal', 'medio'),
  ('13', 'Maciá', 'Villarreal', 'medio'),
  ('14', 'Moleiro', 'Villarreal', 'medio'),
  ('15', 'Buchanan', 'Villarreal', 'delantero'),
  ('16', 'Oluwaseyi', 'Villarreal', 'delantero'),
  ('17', 'Ayoze', 'Villarreal', 'delantero'),
  ('18', 'Pépé', 'Villarreal', 'delantero'),
  ('19', 'Mikautadze', 'Villarreal', 'delantero'),
  ('20', 'Gerard Moreno', 'Villarreal', 'delantero'),
  ('1', 'Antony (Betis)', 'Adn / Laliga Prime', 'delantero'),
  ('2', 'Bellingham (Real Madrid)', 'Adn / Laliga Prime', 'medio'),
  ('3', 'Courtois (Real Madrid)', 'Adn / Laliga Prime', 'portero'),
  ('4', 'Fermín (Barcelona)', 'Adn / Laliga Prime', 'medio'),
  ('5', 'Julián Alvarez (Atlético)', 'Adn / Laliga Prime', 'delantero'),
  ('6', 'Lamine Yamal (Barcelona)', 'Adn / Laliga Prime', 'delantero'),
  ('7', 'Lookman (Atlético)', 'Adn / Laliga Prime', 'delantero'),
  ('8', 'Mbappé (Real Madrid)', 'Adn / Laliga Prime', 'delantero'),
  ('9', 'Moleiro (Villarreal)', 'Adn / Laliga Prime', 'medio'),
  ('10', 'Nico Williams (Athletic)', 'Adn / Laliga Prime', 'delantero'),
  ('11', 'Oyarzabal (Real Sociedad)', 'Adn / Laliga Prime', 'delantero'),
  ('12', 'Pedri (Barcelona)', 'Adn / Laliga Prime', 'medio'),
  ('13', 'Raphinha (Barcelona)', 'Adn / Laliga Prime', 'delantero'),
  ('14', 'Unai Simón (Athletic)', 'Adn / Laliga Prime', 'portero'),
  ('15', 'Vinícius (Real Madrid)', 'Adn / Laliga Prime', 'delantero'),
  ('1', 'Hansi Flick (Barcelona)', 'Laliga Fantasy', 'entrenador'),
  ('2', 'Joan García (Barcelona)', 'Laliga Fantasy', 'portero'),
  ('3', 'Lejeune (Rayo Vallecano)', 'Laliga Fantasy', 'defensa'),
  ('4', 'Fornals (Betis)', 'Laliga Fantasy', 'medio'),
  ('5', 'Lamine Yamal (Barcelona)', 'Laliga Fantasy', 'delantero'),
  ('6', 'Luis Milla (Getafe)', 'Laliga Fantasy', 'medio'),
  ('7', 'Pedri (Barcelona)', 'Laliga Fantasy', 'medio'),
  ('8', 'Luis Milla (Getafe)', 'Laliga Fantasy', 'medio'),
  ('9', 'Mbappé (Real Madrid)', 'Laliga Fantasy', 'delantero'),
  ('1', 'Asencio (Real Madrid)', 'Draft 23', 'defensa'),
  ('2', 'Balde (Barcelona)', 'Draft 23', 'defensa'),
  ('3', 'Barrios (Atlético de Madrid)', 'Draft 23', 'medio'),
  ('4', 'Carlos Espí (Levante)', 'Draft 23', 'delantero'),
  ('5', 'Carreras (Real Madrid)', 'Draft 23', 'defensa'),
  ('6', 'Cubarsí (Barcelona)', 'Draft 23', 'defensa'),
  ('7', 'Fer López (Celta)', 'Draft 23', 'medio'),
  ('8', 'Gavi (Barcelona)', 'Draft 23', 'medio'),
  ('9', 'Gonzalo (Real Madrid)', 'Draft 23', 'delantero'),
  ('10', 'Huijsen (Real Madrid)', 'Draft 23', 'defensa'),
  ('11', 'Jauregizar (Athletic)', 'Draft 23', 'medio'),
  ('12', 'Javi Guerra (Valencia)', 'Draft 23', 'medio'),
  ('13', 'Jon Martín (Real Sociedad)', 'Draft 23', 'defensa'),
  ('14', 'Juanlu (Sevilla)', 'Draft 23', 'defensa'),
  ('15', 'Marc Bernal (Barcelona)', 'Draft 23', 'medio'),
  ('16', 'Mastantuono (Real Madrid)', 'Draft 23', 'medio'),
  ('17', 'Oso (Sevilla)', 'Draft 23', 'medio'),
  ('18', 'Pau Navarro (Villarreal)', 'Draft 23', 'defensa'),
  ('19', 'Pubill (Atlético de Madrid)', 'Draft 23', 'defensa'),
  ('20', 'Renato Veiga (Villarreal)', 'Draft 23', 'defensa'),
  ('21', 'Rodri Mendoza (Atlético de', 'Draft 23', null),
  ('22', 'Thiago Pitarch (Real Madrid)', 'Draft 23', 'medio'),
  ('23', 'Yeremay (Deportivo)', 'Draft 23', 'delantero'),
  ('K1', 'Asencio (Real Madrid)', 'Draft 23 Kromix', 'defensa'),
  ('K2', 'Balde (Barcelona)', 'Draft 23 Kromix', 'defensa'),
  ('K3', 'Barrios (Atlético de Madrid)', 'Draft 23 Kromix', 'medio'),
  ('K4', 'Carlos Espí (Levante)', 'Draft 23 Kromix', 'delantero'),
  ('K5', 'Carreras (Real Madrid)', 'Draft 23 Kromix', 'defensa'),
  ('K6', 'Cubarsí (Barcelona)', 'Draft 23 Kromix', 'defensa'),
  ('K7', 'Fer López (Celta)', 'Draft 23 Kromix', 'medio'),
  ('K8', 'Gavi (Barcelona)', 'Draft 23 Kromix', 'medio'),
  ('K9', 'Gonzalo (Real Madrid)', 'Draft 23 Kromix', 'delantero'),
  ('K10', 'Huijsen (Real Madrid)', 'Draft 23 Kromix', 'defensa'),
  ('K11', 'Jauregizar (Athletic)', 'Draft 23 Kromix', 'medio'),
  ('K12', 'Javi Guerra (Valencia)', 'Draft 23 Kromix', 'medio'),
  ('K13', 'Jon Martín (Real Sociedad)', 'Draft 23 Kromix', 'defensa'),
  ('K14', 'Juanlu (Sevilla)', 'Draft 23 Kromix', 'defensa'),
  ('K15', 'Marc Bernal (Barcelona)', 'Draft 23 Kromix', 'medio'),
  ('K16', 'Mastantuono (Real Madrid)', 'Draft 23 Kromix', 'medio'),
  ('K17', 'Oso (Sevilla)', 'Draft 23 Kromix', 'medio'),
  ('K18', 'Pau Navarro (Villarreal)', 'Draft 23 Kromix', 'defensa'),
  ('K19', 'Pubill (Atlético de Madrid)', 'Draft 23 Kromix', 'defensa'),
  ('K20', 'Renato Veiga (Villarreal)', 'Draft 23 Kromix', 'defensa'),
  ('K21', 'Rodri Mendoza (Atlético de', 'Draft 23 Kromix', null),
  ('K22', 'Thiago Pitarch (Real Madrid)', 'Draft 23 Kromix', 'medio'),
  ('K23', 'Yeremay (Deportivo)', 'Draft 23 Kromix', 'delantero'),
  ('EXTRA-1', 'Lamine Yamal (Barcelona)', 'Extra Sticker Bronce', null),
  ('EXTRA-2', 'Mbappé (Real Madrid)', 'Extra Sticker Bronce', null),
  ('EXTRA-3', 'Nico Williams (Athletic)', 'Extra Sticker Bronce', null),
  ('EXTRA-4', 'Pedri (Barcelona)', 'Extra Sticker Bronce', null),
  ('EXTRA-5', 'Oblak (Atlético de Madrid)', 'Extra Sticker Bronce', null),
  ('EXTRA-1', 'Lamine Yamal (Barcelona)', 'Extra Sticker Plata', null),
  ('EXTRA-2', 'Mbappé (Real Madrid)', 'Extra Sticker Plata', null),
  ('EXTRA-3', 'Nico Williams (Athletic)', 'Extra Sticker Plata', null),
  ('EXTRA-4', 'Pedri (Barcelona)', 'Extra Sticker Plata', null),
  ('EXTRA-5', 'Oblak (Atlético de Madrid)', 'Extra Sticker Plata', null),
  ('EXTRA-1', 'Lamine Yamal (Barcelona)', 'Extra Sticker Oro', null),
  ('EXTRA-2', 'Mbappé (Real Madrid)', 'Extra Sticker Oro', null),
  ('EXTRA-3', 'Nico Williams (Athletic)', 'Extra Sticker Oro', null),
  ('EXTRA-4', 'Pedri (Barcelona)', 'Extra Sticker Oro', null),
  ('EXTRA-5', 'Oblak (Atlético de Madrid)', 'Extra Sticker Oro', null)
) as v(number, name, team, category)
where c.slug = 'laliga-este-2026-27'
on conflict (collection_id, number, team) do update
set name = excluded.name, category = excluded.category;
