import Link from "next/link";
import {redirect} from "next/navigation";
import {ArrowRight,Bell,CircleCheck,Plus,Repeat2,ShoppingBag,Sparkles} from "lucide-react";
import AppHeader from "@/components/app-header";
import {createClient} from "@/lib/supabase/server";
export const dynamic="force-dynamic";
type Match={compatibility_score:number};
type Recent={sticker_id:string;status:"wanted"|"duplicate";updated_at:string;sticker:{number:string;name:string|null;team:string}|{number:string;name:string|null;team:string}[]|null};

export default async function Dashboard(){
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const{data:profile}=await supabase.from("profiles").select("display_name,username").eq("id",user.id).single();
  const{data:collection}=await supabase.from("collections").select("id,name").eq("slug","laliga-este-2026-27").single();
  const[{count:wanted},{count:duplicates},{data:matches},{count:proposals},{count:requests},{count:activeTrades},{data:recentRows}]=await Promise.all([
    supabase.from("user_stickers").select("*",{count:"exact",head:true}).eq("user_id",user.id).eq("status","wanted"),
    supabase.from("user_stickers").select("*",{count:"exact",head:true}).eq("user_id",user.id).eq("status","duplicate"),
    collection?supabase.rpc("get_user_matches",{p_collection_id:collection.id}):Promise.resolve({data:[]}),
    supabase.from("trade_proposals").select("*",{count:"exact",head:true}).eq("recipient_id",user.id).eq("status","pending"),
    supabase.from("market_requests").select("*",{count:"exact",head:true}).eq("status","pending"),
    supabase.from("trade_proposals").select("*",{count:"exact",head:true}).eq("status","accepted").or("fulfillment_status.is.null,fulfillment_status.neq.completed"),
    supabase.from("user_stickers").select("sticker_id,status,updated_at,sticker:stickers(number,name,team)").eq("user_id",user.id).order("updated_at",{ascending:false}).limit(4),
  ]);
  const matchRows=(matches??[]) as Match[],alerts=(proposals??0)+(requests??0),name=profile?.display_name||profile?.username||"coleccionista",recent=(recentRows??[]) as Recent[];
  return <div className="min-h-screen pb-24 md:pb-12"><AppHeader active="home"/><main className="mx-auto max-w-6xl px-4 py-9 md:px-8 md:py-14">
    <section className="relative overflow-hidden rounded-[2rem] bg-[#173d2a] p-6 text-white shadow-[0_24px_60px_rgba(23,61,42,.2)] md:p-10"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-[#c9f31d]/15 blur-2xl"/><p className="relative text-sm font-bold text-[#c9f31d]">Hola, {name}</p><h1 className="relative mt-2 max-w-2xl text-4xl font-black tracking-[-.055em] md:text-6xl">Tu colección está en movimiento.</h1><p className="relative mt-4 max-w-xl text-white/65">Revisa tus oportunidades, responde a otros coleccionistas y sigue acercándote a completar el álbum.</p><div className="relative mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/mi-coleccion" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#c9f31d] px-5 py-3 font-black text-[#173d2a]"><Plus size={18}/>Añadir cromos</Link><Link href="/mercado" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 px-5 py-3 font-bold">Publicar en el mercado<ArrowRight size={18}/></Link></div></section>
    <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat icon={<Sparkles/>} value={wanted??0} label="Me faltan" tone="coral"/><Stat icon={<Repeat2/>} value={duplicates??0} label="Repetidos" tone="lime"/><Stat icon={<CircleCheck/>} value={matchRows.length} label="Matches activos" tone="green"/><Stat icon={<Bell/>} value={alerts} label="Avisos pendientes" tone="dark"/></section>
    <div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="surface rounded-3xl p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#6d7e73]">Actividad reciente</p><h2 className="mt-1 text-2xl font-black">Últimos cromos</h2></div><Link href="/mi-coleccion" className="text-xs font-black text-[#287051]">Ver colección</Link></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{recent.map(row=>{const sticker=Array.isArray(row.sticker)?row.sticker[0]:row.sticker;return <div key={row.sticker_id} className="flex items-center gap-3 rounded-2xl bg-[#fbfaf5] p-3"><span className={`grid h-12 w-12 place-items-center rounded-xl font-mono text-xs font-black ${row.status==="wanted"?"bg-[#ff6a3d] text-white":"bg-[#c9f31d] text-[#17231b]"}`}>#{sticker?.number}</span><span className="min-w-0"><strong className="block truncate text-sm">{sticker?.name||sticker?.team}</strong><small className="block truncate text-[#718078]">{row.status==="wanted"?"Me falta":"Repetido"}</small></span></div>})}{!recent.length&&<Empty text="Marca tus primeros cromos para ver aquí tu actividad."/>}</div></section>
      <section className="rounded-3xl bg-[#e5efd9] p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-[#287051]">Intercambios</p><p className="mt-3 text-5xl font-black">{activeTrades??0}</p><p className="mt-1 font-bold">operaciones actualmente en curso</p><div className="mt-5 space-y-2"><Action href="/mis-matches" icon={<Repeat2/>} title="Propuestas y seguimiento" detail={proposals?`${proposals} pendiente${proposals===1?"":"s"}`:"Todo al día"}/><Action href="/mercado/solicitudes" icon={<ShoppingBag/>} title="Solicitudes del mercado" detail={requests?`${requests} pendiente${requests===1?"":"s"}`:"Sin solicitudes nuevas"}/></div></section></div>
  </main></div>;
}
function Stat({icon,value,label,tone}:{icon:React.ReactNode;value:number;label:string;tone:"coral"|"lime"|"green"|"dark"}){const colors={coral:"bg-[#fff0e9] text-[#ce4a24]",lime:"bg-[#eff8c8] text-[#536500]",green:"bg-[#e3f0e9] text-[#287051]",dark:"bg-[#e8ebe8] text-[#173d2a]"};return <article className="surface rounded-2xl p-4 md:p-5"><div className={`grid h-10 w-10 place-items-center rounded-xl ${colors[tone]}`}>{icon}</div><strong className="mt-4 block text-3xl font-black">{value}</strong><span className="text-xs font-bold text-[#718078]">{label}</span></article>}
function Action({href,icon,title,detail}:{href:string;icon:React.ReactNode;title:string;detail:string}){return <Link href={href} className="flex items-center gap-3 rounded-2xl bg-white p-3 transition hover:-translate-y-0.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#17231b] text-[#c9f31d]">{icon}</span><span className="min-w-0 flex-1"><strong className="block text-xs">{title}</strong><small className="text-[#718078]">{detail}</small></span></Link>}
function Empty({text}:{text:string}){return <div className="col-span-full rounded-2xl border border-dashed border-[#173d2a]/20 p-8 text-center text-sm text-[#65756b]">{text}</div>}
