import Link from"next/link";import{redirect}from"next/navigation";import{ArrowLeft,CreditCard,ShieldCheck}from"lucide-react";import{createClient}from"@/lib/supabase/server";import{stripeRequest,stripeV2Request}from"@/lib/stripe";import RequestActions from"./request-actions";import{CheckoutActions,ConnectPayments,OrderActions}from"./payment-actions";
export const dynamic="force-dynamic";
type Search={checkout?:string;session_id?:string;stripe?:string};type Relation<T>=T|T[]|null;const one=<T,>(v:Relation<T>)=>Array.isArray(v)?v[0]??null:v;

export default async function RequestsPage({searchParams}:{searchParams:Promise<Search>}){
  const params=await searchParams,supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  let banner="";
  if(params.checkout==="success"&&params.session_id){
    try{const session=await stripeRequest<{id:string;payment_status:string;payment_intent:string|null}>(`/checkout/sessions/${encodeURIComponent(params.session_id)}`,undefined,"GET");if(session.payment_status==="paid"&&session.payment_intent){const{error}=await supabase.rpc("confirm_market_order_payment",{p_checkout_session_id:session.id,p_payment_intent_id:session.payment_intent});if(error&&!error.message.includes("unavailable"))throw error;banner="Pago de prueba confirmado correctamente.";}else banner="Stripe todavía no ha confirmado el pago.";}catch(error){banner=error instanceof Error?error.message:"No se pudo confirmar el pago.";}
  }else if(params.checkout==="cancelled")banner="Pago cancelado. No se ha realizado ningún cargo.";
  if(params.stripe){
    try{const{data:account}=await supabase.from("payment_accounts").select("stripe_account_id").eq("user_id",user.id).maybeSingle();if(account){const stripe=await stripeV2Request<{configuration?:{recipient?:{capabilities?:{stripe_balance?:{stripe_transfers?:{status?:string}}}}}}>(`/core/accounts/${account.stripe_account_id}?include%5B0%5D=configuration.recipient&include%5B1%5D=requirements`,undefined,"GET");const ready=stripe.configuration?.recipient?.capabilities?.stripe_balance?.stripe_transfers?.status==="active";await supabase.rpc("update_payment_account_status",{p_charges:ready,p_payouts:ready,p_complete:ready});banner=ready?"Tu cuenta ya puede recibir cobros.":"Stripe todavía necesita algunos datos para habilitar tus cobros.";}}catch{banner="No se pudo actualizar el estado de Stripe.";}
  }
  const[{data:requests},{data:payment},{data:orders}]=await Promise.all([
    supabase.from("market_requests").select("id,buyer_id,status,created_at,buyer:profiles!market_requests_buyer_id_fkey(display_name,username),listing:market_listings(id,seller_id,price_cents,sticker:stickers(number,name,team))").order("created_at",{ascending:false}),
    supabase.from("payment_accounts").select("charges_enabled,payouts_enabled,onboarding_complete").eq("user_id",user.id).maybeSingle(),
    supabase.from("market_orders").select("id,request_id,buyer_id,seller_id,item_cents,shipping_cents,total_cents,delivery_method,payment_status,carrier,tracking_code,shipped_at,received_at")
  ]);
  const orderByRequest=new Map((orders??[]).map(order=>[order.request_id,order]));
  return <main className="min-h-screen bg-[#f5f2e9] px-4 py-8"><div className="mx-auto max-w-3xl"><Link href="/mercado" className="flex items-center gap-2 text-sm font-bold"><ArrowLeft size={18}/>Mercado</Link><div className="mt-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#527060]">Compras seguras · modo de prueba</p><h1 className="mt-2 text-4xl font-black">Solicitudes y pedidos</h1></div><ConnectPayments/></div>
  <div className="mt-5 rounded-2xl border border-[#635bff]/20 bg-white p-4 text-sm"><p className="flex items-center gap-2 font-black"><ShieldCheck size={17} className="text-[#635bff]"/>Stripe Connect</p><p className="mt-1 text-[#65756b]">{payment?.charges_enabled&&payment.payouts_enabled?"Tus cobros están habilitados.":"Configura Stripe para poder recibir el importe de tus ventas."}</p></div>
  {banner&&<p className="mt-4 rounded-xl bg-[#edf7d6] p-3 text-sm font-bold">{banner}</p>}
  <div className="mt-6 space-y-3">{(requests??[]).map(request=>{const listing=one(request.listing),sticker=listing?one(listing.sticker):null,buyer=one(request.buyer),incoming=listing?.seller_id===user.id,order=orderByRequest.get(request.id);return <article key={request.id} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="font-black">#{sticker?.number} · {sticker?.name??sticker?.team}</p><p className="mt-1 text-sm text-[#6b786f]">{incoming?`Solicitud de ${buyer?.display_name||buyer?.username||"Coleccionista"}`:"Tu solicitud de compra"}</p></div><div className="text-right"><p className="font-black">{listing?`${(listing.price_cents/100).toFixed(2).replace(".",",")} €`:""}</p><span className="text-xs font-bold uppercase">{order?.payment_status==="paid"?"pagado":request.status}</span></div></div>
  {incoming&&request.status==="pending"&&<RequestActions requestId={request.id}/>} {!incoming&&request.status==="accepted"&&!order&&<CheckoutActions requestId={request.id}/>} {order&&<div className="mt-4 rounded-xl bg-[#f7f8f6] p-4"><p className="flex items-center gap-2 text-sm font-black"><CreditCard size={17}/>{order.payment_status==="paid"?"Pago confirmado":"Pago pendiente"} · {(order.total_cents/100).toFixed(2).replace(".",",")} €</p><p className="mt-1 text-xs text-[#718078]">{order.delivery_method==="shipping"?"Envío certificado con seguimiento":"Entrega en mano"}{order.tracking_code?` · ${order.carrier}: ${order.tracking_code}`:""}</p>{order.payment_status==="paid"&&<OrderActions orderId={order.id} incoming={incoming} delivery={order.delivery_method} shipped={Boolean(order.shipped_at)} received={Boolean(order.received_at)}/>}</div>}</article>})}{!requests?.length&&<p className="rounded-2xl border border-dashed p-10 text-center">Todavía no tienes solicitudes.</p>}</div></div></main>;
}
